services:
  postgres:
    image: postgres:16-alpine
    container_name: catu_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: catu_v2_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: catu_backend
    restart: always
    ports:
      - "3005:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: catu_v2_db
      PORT: 3000
    volumes:
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json
    depends_on:
      - postgres

  admin_web:
    build:
      context: ./admin_web
      dockerfile: Dockerfile
    container_name: catu_admin_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./admin_web:/usr/share/nginx/html
    depends_on:
      - backend

  searxng:
    image: searxng/searxng:latest
    container_name: catu_searxng
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET_KEY=catu_super_secret_key_2026
      - SEARXNG_BIND_ADDRESS=0.0.0.0:8080

volumes:
  postgres_data:
