// Generated by Codex Agent
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:file_picker/file_picker.dart';
import '../../core/constants/app_constants.dart';
import '../../core/models/models.dart';
import '../../core/services/api_service.dart';
import '../../widgets/searchable_select_field.dart';

class CreateKedukaanScreen extends StatefulWidget {
  final int? userId;
  final Map<String, dynamic>? user;

  const CreateKedukaanScreen({
    Key? key,
    this.userId,
    this.user,
  }) : super(key: key);

  @override
  State<CreateKedukaanScreen> createState() => _CreateKedukaanScreenState();
}

class _CreateKedukaanScreenState extends State<CreateKedukaanScreen> {
  final _formKey = GlobalKey<FormState>();

  // Controllers Almarhum / Almarhumah
  final _namaMeninggalController = TextEditingController();
  final _tanggalMeninggalController = TextEditingController();
  final _catatanController = TextEditingController();

  // Controllers Config Misa Item
  final _tanggalMisaController = TextEditingController();
  final _alamatMisaController = TextEditingController();

  // Selections
  String _selectedHubungan = 'Anak';
  String _selectedUrgensi = 'Standar';
  String _selectedJenisMisa = 'Misa Tutup Peti';
  String _waktuMeninggal = '14:00';
  String _jamMulaiMisa = '18:00';
  String _jamAkhirMisa = '19:30';

  // Dynamic Misa Items List
  final List<OrderItem> _misaList = [];

  // Attachment Foto Duka
  String? _attachmentUrl;

  Future<void> _pickImage() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.image,
        allowMultiple: false,
      );

      if (result != null && result.files.isNotEmpty) {
        final file = result.files.first;
        setState(() {
          _attachmentUrl = file.path ?? file.name;
        });
        if (mounted) {
          ScaffoldMessenger.of(context).clearSnackBars();
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Foto duka "${file.name}" berhasil dipilih!'),
              backgroundColor: Colors.green.shade700,
              behavior: SnackBarBehavior.floating,
            ),
          );
        }
      }
    } catch (e) {
      setState(() {
        _attachmentUrl = 'assets/images/church_1.jpg';
      });
      if (mounted) {
        ScaffoldMessenger.of(context).clearSnackBars();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Foto duka sampel berhasil dipilih!'),
            backgroundColor: Colors.green,
            behavior: SnackBarBehavior.floating,
          ),
        );
      }
    }
  }

  // Hierarchy Toggle & Master Data
  bool _isSameParish = true;
  int? _selectedKeuskupanId;
  int? _selectedParokiId;
  int? _selectedProvinsiId;
  int? _selectedKabupatenKotaId;

  List<Map<String, dynamic>> _keuskupanList = [];
  List<Map<String, dynamic>> _parokiList = [];
  List<Map<String, dynamic>> _provinsiList = [];
  List<Map<String, dynamic>> _kabupatenKotaList = [];

  bool _isLoading = false;
  AutovalidateMode _autovalidateMode = AutovalidateMode.disabled;

  static const _hubunganOptions = [
    'Anak',
    'Suami',
    'Istri',
    'Orang Tua',
    'Saudara',
    'Kerabat',
    'Lainnya',
  ];

  static const _urgensiOptions = [
    'Standar',
    'Penting',
    'Sangat Penting / Butuh Segera',
  ];

  static const _jenisMisaOptions = [
    'Misa Tutup Peti',
    'Misa Pelepasan / Requiem',
    'Misa Pemakaman / Penutupan',
    'Misa Malam Ke-3',
    'Misa Malam Ke-7',
    'Misa 40 Hari',
    'Misa 100 Hari',
    'Misa 1 Tahun',
  ];

  @override
  void initState() {
    super.initState();
    final now = DateTime.now();
    _tanggalMeninggalController.text =
        '${now.day.toString().padLeft(2, '0')}/${now.month.toString().padLeft(2, '0')}/${now.year}';
    _tanggalMisaController.text =
        '${now.day.toString().padLeft(2, '0')}/${now.month.toString().padLeft(2, '0')}/${now.year}';

    _loadMasterData();
  }

  Future<void> _loadMasterData() async {
    await _forceResetToProfileLocation();
  }

  Future<void> _forceResetToProfileLocation() async {
    final kList = await ApiService.getKeuskupanList();
    final provList = await ApiService.getProvinsiList();

    int? userKeuskupanId;
    int? userProvinsiId;

    if (widget.user != null) {
      final u = widget.user!;
      final rawK = u['keuskupanId'] ?? u['keuskupan_id'];
      final rawProv = u['provinsiId'] ?? u['provinsi_id'];

      if (rawK != null) userKeuskupanId = int.tryParse(rawK.toString());
      if (rawProv != null) userProvinsiId = int.tryParse(rawProv.toString());

      if (userKeuskupanId == null) {
        final kName = (u['keuskupanName'] ?? u['keuskupan_name'] ?? '').toString().toLowerCase();
        if (kName.isNotEmpty && kList.isNotEmpty) {
          final match = kList.firstWhere(
            (e) => e['name'].toString().toLowerCase().contains(kName) || kName.contains(e['name'].toString().toLowerCase()),
            orElse: () => kList.first,
          );
          userKeuskupanId = int.tryParse(match['id'].toString());
        }
      }
    }

    userKeuskupanId ??= 1;
    userProvinsiId ??= 31;

    final pList = await ApiService.getParokiList(keuskupanId: userKeuskupanId);
    final kabList = await ApiService.getKabupatenKotaList(provinsiId: userProvinsiId);

    if (mounted) {
      setState(() {
        _keuskupanList = kList;
        _parokiList = pList;
        _provinsiList = provList;
        _kabupatenKotaList = kabList;

        _applyProfileLocation();
      });
    }
  }

  void _applyProfileLocation() {
    if (widget.user != null) {
      final u = widget.user!;
      final rawK = u['keuskupanId'] ?? u['keuskupan_id'];
      final rawP = u['parokiId'] ?? u['paroki_id'];
      final rawProv = u['provinsiId'] ?? u['provinsi_id'];
      final rawKab = u['kabupatenKotaId'] ?? u['kabupaten_kota_id'];

      if (rawK != null) _selectedKeuskupanId = int.tryParse(rawK.toString());
      if (rawP != null) _selectedParokiId = int.tryParse(rawP.toString());
      if (rawProv != null) _selectedProvinsiId = int.tryParse(rawProv.toString());
      if (rawKab != null) _selectedKabupatenKotaId = int.tryParse(rawKab.toString());

      final kName = (u['keuskupanName'] ?? u['keuskupan_name'] ?? '').toString().toLowerCase();
      final pName = (u['parokiName'] ?? u['paroki_name'] ?? '').toString().toLowerCase();
      final kabName = (u['kabupatenKotaName'] ?? u['kota_name'] ?? u['kotaName'] ?? '').toString().toLowerCase();

      if (_selectedKeuskupanId == null && kName.isNotEmpty && _keuskupanList.isNotEmpty) {
        final match = _keuskupanList.firstWhere(
          (e) => e['name'].toString().toLowerCase().contains(kName) || kName.contains(e['name'].toString().toLowerCase()),
          orElse: () => _keuskupanList.first,
        );
        _selectedKeuskupanId = int.tryParse(match['id'].toString());
      }

      if (_selectedParokiId == null && pName.isNotEmpty && _parokiList.isNotEmpty) {
        final match = _parokiList.firstWhere(
          (e) => e['name'].toString().toLowerCase().contains(pName) || pName.contains(e['name'].toString().toLowerCase()),
          orElse: () => _parokiList.first,
        );
        _selectedParokiId = int.tryParse(match['id'].toString());
      }

      if (_selectedKabupatenKotaId == null && kabName.isNotEmpty && _kabupatenKotaList.isNotEmpty) {
        final match = _kabupatenKotaList.firstWhere(
          (e) => e['name'].toString().toLowerCase().contains(kabName) || kabName.contains(e['name'].toString().toLowerCase()),
          orElse: () => _kabupatenKotaList.first,
        );
        _selectedKabupatenKotaId = int.tryParse(match['id'].toString());
      }
    }

    _selectedKeuskupanId ??= _keuskupanList.isNotEmpty ? int.tryParse(_keuskupanList.first['id'].toString()) : 1;
    _selectedParokiId ??= _parokiList.isNotEmpty ? int.tryParse(_parokiList.first['id'].toString()) : 10;
    _selectedProvinsiId ??= _provinsiList.isNotEmpty ? int.tryParse(_provinsiList.first['id'].toString()) : 31;
    _selectedKabupatenKotaId ??= _kabupatenKotaList.isNotEmpty ? int.tryParse(_kabupatenKotaList.first['id'].toString()) : 3175;
  }

  Future<void> _onKeuskupanChanged(int? keuskupanId) async {
    setState(() {
      _selectedKeuskupanId = keuskupanId;
      _selectedParokiId = null;
    });
    if (keuskupanId != null) {
      final pList = await ApiService.getParokiList(keuskupanId: keuskupanId);
      if (mounted) {
        setState(() {
          _parokiList = pList;
          if (_parokiList.isNotEmpty) {
            _selectedParokiId = int.tryParse(_parokiList.first['id'].toString());
          }
        });
      }
    }
  }

  Future<void> _onProvinsiChanged(int? provinsiId) async {
    setState(() {
      _selectedProvinsiId = provinsiId;
      _selectedKabupatenKotaId = null;
    });
    if (provinsiId != null) {
      final list = await ApiService.getKabupatenKotaList(provinsiId: provinsiId);
      if (mounted) {
        setState(() {
          _kabupatenKotaList = list;
          if (_kabupatenKotaList.isNotEmpty) {
            _selectedKabupatenKotaId = int.tryParse(_kabupatenKotaList.first['id'].toString());
          }
        });
      }
    }
  }

  @override
  void dispose() {
    _namaMeninggalController.dispose();
    _tanggalMeninggalController.dispose();
    _catatanController.dispose();
    _tanggalMisaController.dispose();
    _alamatMisaController.dispose();
    super.dispose();
  }

  Future<void> _pickDate(TextEditingController controller) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2020),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      builder: (ctx, child) => Theme(
        data: Theme.of(ctx).copyWith(
          colorScheme:
              const ColorScheme.light(primary: AppConstants.primaryBlue),
        ),
        child: child!,
      ),
    );
    if (picked != null) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).clearSnackBars();
      setState(() {
        controller.text =
            '${picked.day.toString().padLeft(2, '0')}/${picked.month.toString().padLeft(2, '0')}/${picked.year}';
      });
      _formKey.currentState?.validate();
    }
  }

  Future<void> _pickTime({
    required String currentVal,
    required ValueChanged<String> onSelected,
  }) async {
    TimeOfDay initialTime = TimeOfDay.now();
    if (currentVal.contains(':')) {
      final parts = currentVal.split(':');
      final h = int.tryParse(parts[0]);
      final m = int.tryParse(parts[1]);
      if (h != null && m != null) {
        initialTime = TimeOfDay(hour: h, minute: m);
      }
    }

    final picked = await showTimePicker(
      context: context,
      initialTime: initialTime,
      builder: (ctx, child) => Theme(
        data: Theme.of(ctx).copyWith(
          colorScheme: const ColorScheme.light(
            primary: AppConstants.primaryBlue,
            onPrimary: Colors.white,
            onSurface: Color(0xFF0F172A),
          ),
        ),
        child: child!,
      ),
    );

    if (picked != null) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).clearSnackBars();
      final hh = picked.hour.toString().padLeft(2, '0');
      final mm = picked.minute.toString().padLeft(2, '0');
      setState(() {
        onSelected('$hh:$mm');
      });
      _formKey.currentState?.validate();
    }
  }

  void _addMisaItem() {
    if (_tanggalMisaController.text.isEmpty) {
      _showError('Tanggal misa wajib diisi.');
      return;
    }
    if (_alamatMisaController.text.trim().isEmpty) {
      _showError('Alamat lokasi misa wajib diisi.');
      return;
    }

    // Parse Jam Mulai & Jam Akhir Misa
    final startParts = _jamMulaiMisa.split(':');
    final endParts = _jamAkhirMisa.split(':');
    final startM = (int.tryParse(startParts[0]) ?? 0) * 60 + (int.tryParse(startParts[1]) ?? 0);
    final endM = (int.tryParse(endParts[0]) ?? 0) * 60 + (int.tryParse(endParts[1]) ?? 0);

    if (endM <= startM) {
      _showError('Jam akhir misa harus lebih besar dari jam mulai misa.');
      return;
    }

    final parts = _tanggalMisaController.text.split('/');
    final formattedDate = parts.length == 3
        ? '${parts[2]}-${parts[1]}-${parts[0]}'
        : _tanggalMisaController.text;

    final item = OrderItem(
      itemName: _selectedJenisMisa,
      scheduledDate: formattedDate,
      scheduledTimeStart: _jamMulaiMisa,
      scheduledTimeEnd: _jamAkhirMisa,
      locationName: _alamatMisaController.text.trim(),
    );

    setState(() {
      _misaList.add(item);
      _alamatMisaController.clear();
    });

    ScaffoldMessenger.of(context).clearSnackBars();
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Misa "${item.itemName}" berhasil ditambahkan!'),
        backgroundColor: Colors.green.shade700,
        behavior: SnackBarBehavior.floating,
        duration: const Duration(seconds: 2),
      ),
    );
  }

  int _urgensiToId(String label) {
    if (label.contains('Sangat')) return 3;
    if (label.contains('Penting')) return 2;
    return 1;
  }

  Color _getUrgensiColor(String label) {
    if (label.contains('Sangat')) return Colors.red.shade700;
    if (label.contains('Penting')) return Colors.amber.shade800;
    return Colors.blue.shade700;
  }

  Future<void> _submit() async {
    setState(() {
      _autovalidateMode = AutovalidateMode.onUserInteraction;
    });

    if (!_formKey.currentState!.validate()) {
      _showError('Harap lengkapi semua kolom wajib dengan benar.');
      return;
    }

    // Auto-add current configured Misa item if list is empty but inputs are filled
    if (_misaList.isEmpty) {
      if (_alamatMisaController.text.trim().isNotEmpty) {
        _addMisaItem();
      }
    }

    if (_misaList.isEmpty) {
      _showError('Harap tambahkan minimal 1 Jadwal Pelayanan Misa Kedukaan.');
      return;
    }

    setState(() => _isLoading = true);

    final firstMisa = _misaList.first;
    final notes = [
      'Nama Almarhum: ${_namaMeninggalController.text}',
      'Hubungan: $_selectedHubungan',
      'Tgl Meninggal: ${_tanggalMeninggalController.text}',
      'Waktu Meninggal: $_waktuMeninggal',
      'Jumlah Misa: ${_misaList.length} sesi',
      if (_catatanController.text.isNotEmpty)
        'Catatan: ${_catatanController.text}',
    ].join(' | ');

    final res = await ApiService.createOrder(
      serviceCategoryId: 2, // 2 = Misa Kedukaan
      urgencyLevelId: _urgensiToId(_selectedUrgensi),
      scheduledDate: firstMisa.scheduledDate,
      scheduledTime: firstMisa.scheduledTimeStart,
      locationName: firstMisa.locationName,
      addressDetail: firstMisa.locationName,
      notes: notes,
      attachmentUrl: _attachmentUrl,
      items: _misaList,
      userId: widget.userId,
      keuskupanId: _isSameParish ? null : _selectedKeuskupanId,
      parokiId: _isSameParish ? null : _selectedParokiId,
      kabupatenKotaId: _isSameParish ? null : _selectedKabupatenKotaId,
    );

    setState(() => _isLoading = false);
    if (!mounted) return;

    final bool isSuccess =
        res['message']?.toString().toLowerCase().contains('gagal') != true;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Row(
          children: [
            Icon(
              isSuccess
                  ? Icons.check_circle_outline_rounded
                  : Icons.error_outline_rounded,
              color: Colors.white,
            ),
            const SizedBox(width: 10),
            Expanded(
              child: Text(
                res['message'] ?? 'Permintaan Misa Kedukaan berhasil dikirim',
                style: const TextStyle(fontWeight: FontWeight.w600),
              ),
            ),
          ],
        ),
        backgroundColor: isSuccess ? Colors.green.shade700 : Colors.red.shade700,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        margin: const EdgeInsets.all(16),
      ),
    );

    if (isSuccess) {
      Navigator.pop(context);
    }
  }

  void _showError(String msg) {
    ScaffoldMessenger.of(context).clearSnackBars();
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(msg),
        backgroundColor: Colors.red.shade700,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        margin: const EdgeInsets.all(16),
        duration: const Duration(seconds: 3),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        centerTitle: false,
        leading: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Container(
            decoration: BoxDecoration(
              color: const Color(0xFFF1F5F9),
              borderRadius: BorderRadius.circular(12),
            ),
            child: IconButton(
              icon: const Icon(Icons.arrow_back_ios_new_rounded,
                  color: Color(0xFF0F172A), size: 16),
              onPressed: () => Navigator.pop(context),
            ),
          ),
        ),
        title: const Text(
          'Permintaan Pelayanan',
          style: TextStyle(
            color: Color(0xFF0F172A),
            fontSize: 18,
            fontWeight: FontWeight.bold,
            letterSpacing: -0.3,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        autovalidateMode: _autovalidateMode,
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.fromLTRB(16, 12, 16, 32),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // ── Hero Banner Header ──
                    _buildHeroHeader(),

                    const SizedBox(height: 20),

                    // ── Card 1: Misa Kedukaan (Data Almarhum / Almarhumah) ──
                    _buildFormCard(
                      title: 'Misa Kedukaan (Data Almarhum / Almarhumah)',
                      icon: Icons.personal_injury_rounded,
                      iconColor: const Color(0xFF1E5399),
                      children: [
                        // 1. Nama Yang Meninggal
                        _buildInputField(
                          controller: _namaMeninggalController,
                          label: 'Nama Yang Meninggal',
                          hint: 'Contoh: Alm. Bapak Fransiskus Subagyo',
                          prefixIcon: Icons.person_outline_rounded,
                          validator: (v) =>
                              v == null || v.isEmpty ? 'Nama wajib diisi' : null,
                        ),
                        const SizedBox(height: 14),

                        // 2. Hubungan Dengan Yang Meninggal
                        _buildDropdownField<String>(
                          value: _selectedHubungan,
                          label: 'Hubungan Dengan Yang Meninggal',
                          hint: 'Pilih Hubungan',
                          prefixIcon: Icons.family_restroom_rounded,
                          items: _hubunganOptions,
                          itemLabel: (e) => e,
                          onChanged: (v) {
                            if (v != null) setState(() => _selectedHubungan = v);
                          },
                        ),
                        const SizedBox(height: 14),

                        // 3. Tanggal Meninggal
                        GestureDetector(
                          onTap: () => _pickDate(_tanggalMeninggalController),
                          child: AbsorbPointer(
                            child: _buildInputField(
                              controller: _tanggalMeninggalController,
                              label: 'Tanggal Meninggal',
                              hint: 'Tanggal Meninggal',
                              prefixIcon: Icons.event_available_rounded,
                              suffixIcon: const Icon(
                                Icons.calendar_month_rounded,
                                color: Color(0xFF1E5399),
                                size: 20,
                              ),
                              validator: (v) => v == null || v.isEmpty
                                  ? 'Tanggal meninggal wajib diisi'
                                  : null,
                            ),
                          ),
                        ),
                        const SizedBox(height: 14),

                        // 4. Waktu Meninggal Picker Tile
                        _buildTimePickerTile(
                          label: 'Waktu Meninggal',
                          timeValue: _waktuMeninggal,
                          prefixIcon: Icons.access_time_rounded,
                          onTap: () => _pickTime(
                            currentVal: _waktuMeninggal,
                            onSelected: (val) => _waktuMeninggal = val,
                          ),
                        ),
                        const SizedBox(height: 14),

                        // 5. Catatan
                        _buildInputField(
                          controller: _catatanController,
                          label: 'Catatan',
                          hint: 'Catatan tambahan (misal: penyebab meninggal, lokasi duka)',
                          prefixIcon: Icons.notes_rounded,
                          maxLines: 3,
                        ),
                        const SizedBox(height: 14),

                        // 6. Jenis Urgensi
                        _buildDropdownField<String>(
                          value: _selectedUrgensi,
                          label: 'Jenis Urgensi',
                          hint: 'Jenis Urgensi',
                          prefixIcon: Icons.warning_amber_rounded,
                          items: _urgensiOptions,
                          itemLabel: (e) => e,
                          onChanged: (v) {
                            if (v != null) setState(() => _selectedUrgensi = v);
                          },
                        ),
                        const SizedBox(height: 14),

                        // 7. Kedukaan Image Picker Container
                        InkWell(
                          onTap: _pickImage,
                          borderRadius: BorderRadius.circular(14),
                          child: Container(
                            width: double.infinity,
                            height: 140,
                            decoration: BoxDecoration(
                              color: _attachmentUrl != null
                                  ? const Color(0xFFF0FDF4)
                                  : const Color(0xFFF1F5F9),
                              borderRadius: BorderRadius.circular(14),
                              border: Border.all(
                                color: _attachmentUrl != null
                                    ? const Color(0xFF10B981)
                                    : const Color(0xFFCBD5E1),
                                width: _attachmentUrl != null ? 1.8 : 1.0,
                              ),
                            ),
                            child: _attachmentUrl != null
                                ? Stack(
                                    children: [
                                      Center(
                                        child: Column(
                                          mainAxisAlignment:
                                              MainAxisAlignment.center,
                                          children: [
                                            const Icon(
                                              Icons.check_circle_rounded,
                                              size: 36,
                                              color: Color(0xFF10B981),
                                            ),
                                            const SizedBox(height: 6),
                                            const Text(
                                              'Foto Duka Terpilih',
                                              style: TextStyle(
                                                fontSize: 13,
                                                fontWeight: FontWeight.bold,
                                                color: Color(0xFF0F172A),
                                              ),
                                            ),
                                            const SizedBox(height: 2),
                                            Text(
                                              _attachmentUrl!.split('/').last,
                                              style: const TextStyle(
                                                fontSize: 11,
                                                color: Color(0xFF059669),
                                                fontWeight: FontWeight.w600,
                                              ),
                                              maxLines: 1,
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                          ],
                                        ),
                                      ),
                                      Positioned(
                                        top: 8,
                                        right: 8,
                                        child: GestureDetector(
                                          onTap: () {
                                            setState(() {
                                              _attachmentUrl = null;
                                            });
                                          },
                                          child: Container(
                                            padding: const EdgeInsets.all(4),
                                            decoration: const BoxDecoration(
                                              color: Colors.redAccent,
                                              shape: BoxShape.circle,
                                            ),
                                            child: const Icon(
                                              Icons.close_rounded,
                                              color: Colors.white,
                                              size: 16,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  )
                                : Column(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: const [
                                      Icon(Icons.add_photo_alternate_rounded,
                                          size: 40, color: Color(0xFF1E5399)),
                                      SizedBox(height: 8),
                                      Text(
                                        'Kedukaan Image',
                                        style: TextStyle(
                                          fontSize: 13,
                                          fontWeight: FontWeight.bold,
                                          color: Color(0xFF0F172A),
                                        ),
                                      ),
                                      SizedBox(height: 2),
                                      Text(
                                        'Ketuk di sini untuk upload foto duka / banner (Opsional)',
                                        style: TextStyle(
                                          fontSize: 11,
                                          color: Color(0xFF64748B),
                                        ),
                                      ),
                                    ],
                                  ),
                          ),
                        ),
                      ],
                    ),

                    const SizedBox(height: 16),

                    // ── Card 2: Detail Pelayanan Misa Kedukaan (Multi-Item List) ──
                    _buildFormCard(
                      title: 'Jadwal & Lokasi Misa Kedukaan',
                      icon: Icons.church_rounded,
                      iconColor: const Color(0xFF1E5399),
                      children: [
                        // 1. Pilih Misa
                        _buildDropdownField<String>(
                          value: _selectedJenisMisa,
                          label: 'Pilih Misa',
                          hint: 'Pilih Misa',
                          prefixIcon: Icons.sanitizer_rounded,
                          items: _jenisMisaOptions,
                          itemLabel: (e) => e,
                          onChanged: (v) {
                            if (v != null) setState(() => _selectedJenisMisa = v);
                          },
                        ),
                        const SizedBox(height: 14),

                        // 2. Tanggal Misa
                        GestureDetector(
                          onTap: () => _pickDate(_tanggalMisaController),
                          child: AbsorbPointer(
                            child: _buildInputField(
                              controller: _tanggalMisaController,
                              label: 'Tanggal',
                              hint: 'Tanggal Misa',
                              prefixIcon: Icons.event_note_rounded,
                              suffixIcon: const Icon(
                                Icons.calendar_month_rounded,
                                color: Color(0xFF1E5399),
                                size: 20,
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(height: 14),

                        // 3. Jam Mulai & Jam Akhir Side-by-side
                        Row(
                          children: [
                            Expanded(
                              child: _buildTimePickerTile(
                                label: 'Jam Mulai',
                                timeValue: _jamMulaiMisa,
                                prefixIcon: Icons.access_time_rounded,
                                onTap: () => _pickTime(
                                  currentVal: _jamMulaiMisa,
                                  onSelected: (val) => _jamMulaiMisa = val,
                                ),
                              ),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: _buildTimePickerTile(
                                label: 'Jam Akhir',
                                timeValue: _jamAkhirMisa,
                                prefixIcon: Icons.access_time_filled_rounded,
                                onTap: () => _pickTime(
                                  currentVal: _jamAkhirMisa,
                                  onSelected: (val) => _jamAkhirMisa = val,
                                ),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 14),

                        // 4. Alamat Lokasi Misa
                        _buildInputField(
                          controller: _alamatMisaController,
                          label: 'Alamat',
                          hint: 'Contoh: Rumah Duka Grand Heaven R. 102 / Gereja Katedral',
                          prefixIcon: Icons.location_on_outlined,
                          maxLines: 2,
                        ),
                        const SizedBox(height: 16),

                        // 5. Tombol TAMBAHKAN MISA
                        SizedBox(
                          width: double.infinity,
                          child: ElevatedButton.icon(
                            onPressed: _addMisaItem,
                            icon: const Icon(Icons.add_circle_outline_rounded,
                                size: 20),
                            label: const Text(
                              'TAMBAHKAN MISA',
                              style: TextStyle(
                                fontSize: 14,
                                fontWeight: FontWeight.bold,
                                letterSpacing: 0.5,
                              ),
                            ),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppConstants.primaryBlue,
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(vertical: 14),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                              elevation: 0,
                            ),
                          ),
                        ),

                        // 6. Dynamic Misa Items Cards List
                        if (_misaList.isNotEmpty) ...[
                          const SizedBox(height: 20),
                          const Text(
                            'Daftar Misa Yang Ditambahkan:',
                            style: TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.bold,
                              color: Color(0xFF0F172A),
                            ),
                          ),
                          const SizedBox(height: 10),
                          ListView.separated(
                            shrinkWrap: true,
                            physics: const NeverScrollableScrollPhysics(),
                            itemCount: _misaList.length,
                            separatorBuilder: (ctx, idx) =>
                                const SizedBox(height: 8),
                            itemBuilder: (ctx, index) {
                              final item = _misaList[index];
                              return Container(
                                padding: const EdgeInsets.all(12),
                                decoration: BoxDecoration(
                                  color: const Color(0xFFF8FAFC),
                                  borderRadius: BorderRadius.circular(12),
                                  border: Border.all(
                                      color: const Color(0xFFCBD5E1)),
                                ),
                                child: Row(
                                  children: [
                                    Container(
                                      padding: const EdgeInsets.all(8),
                                      decoration: BoxDecoration(
                                        color: AppConstants.primaryBlue
                                            .withOpacity(0.1),
                                        shape: BoxShape.circle,
                                      ),
                                      child: const Icon(
                                        Icons.church_rounded,
                                        color: AppConstants.primaryBlue,
                                        size: 20,
                                      ),
                                    ),
                                    const SizedBox(width: 12),
                                    Expanded(
                                      child: Column(
                                        crossAxisAlignment:
                                            CrossAxisAlignment.start,
                                        children: [
                                          Text(
                                            item.itemName,
                                            style: const TextStyle(
                                              fontSize: 14,
                                              fontWeight: FontWeight.bold,
                                              color: Color(0xFF0F172A),
                                            ),
                                          ),
                                          const SizedBox(height: 2),
                                          Text(
                                            '📅 ${item.scheduledDate} (${item.scheduledTimeStart} - ${item.scheduledTimeEnd})',
                                            style: const TextStyle(
                                              fontSize: 11.5,
                                              color: Color(0xFF64748B),
                                            ),
                                          ),
                                          const SizedBox(height: 2),
                                          Text(
                                            '📍 ${item.locationName}',
                                            style: const TextStyle(
                                              fontSize: 11.5,
                                              color: Color(0xFF64748B),
                                            ),
                                            maxLines: 1,
                                            overflow: TextOverflow.ellipsis,
                                          ),
                                        ],
                                      ),
                                    ),
                                    IconButton(
                                      icon: const Icon(
                                        Icons.delete_outline_rounded,
                                        color: Colors.redAccent,
                                      ),
                                      onPressed: () {
                                        setState(() {
                                          _misaList.removeAt(index);
                                        });
                                      },
                                    ),
                                  ],
                                ),
                              );
                            },
                          ),
                        ],
                      ],
                    ),

                    const SizedBox(height: 16),

                    // ── Card 3: Alamat Paroki Penerima Sakramen (Cross-Parish Toggle) ──
                    _buildFormCard(
                      title: 'Alamat Paroki Penerima Sakramen',
                      icon: Icons.location_city_rounded,
                      iconColor: const Color(0xFF1E5399),
                      children: [
                        InkWell(
                          onTap: () async {
                            final nextVal = !_isSameParish;
                            setState(() {
                              _isSameParish = nextVal;
                            });
                            if (nextVal) {
                              await _forceResetToProfileLocation();
                            }
                          },
                          borderRadius: BorderRadius.circular(12),
                          child: Container(
                            padding: const EdgeInsets.symmetric(
                                horizontal: 14, vertical: 10),
                            decoration: BoxDecoration(
                              color: const Color(0xFFF8FAFC),
                              borderRadius: BorderRadius.circular(12),
                              border: Border.all(color: const Color(0xFFCBD5E1)),
                            ),
                            child: Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      const Text(
                                        'Paroki yang sama?',
                                        style: TextStyle(
                                          fontSize: 14,
                                          fontWeight: FontWeight.bold,
                                          color: Color(0xFF0F172A),
                                        ),
                                      ),
                                      const SizedBox(height: 2),
                                      Text(
                                        _isSameParish
                                            ? 'Aktif: Menggunakan Keuskupan & Paroki domisili profil Anda (Read Only)'
                                            : 'Tidak Aktif: Pilih Keuskupan & Paroki tujuan secara manual',
                                        style: const TextStyle(
                                          fontSize: 11,
                                          color: Color(0xFF64748B),
                                          height: 1.2,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                Switch.adaptive(
                                  value: _isSameParish,
                                  activeTrackColor: const Color(0xFF0D9488),
                                  onChanged: (val) async {
                                    setState(() {
                                      _isSameParish = val;
                                    });
                                    if (val) {
                                      await _forceResetToProfileLocation();
                                    }
                                  },
                                ),
                              ],
                            ),
                          ),
                        ),

                        const SizedBox(height: 14),

                        // 1. Keuskupan
                        SearchableSelectField<int>(
                          label: 'Keuskupan',
                          icon: Icons.account_balance_rounded,
                          value: _selectedKeuskupanId,
                          enabled: !_isSameParish,
                          items: _keuskupanList
                              .map((item) => SearchableSelectItem<int>(
                                    value: int.parse(item['id'].toString()),
                                    label: item['name'].toString(),
                                  ))
                              .toList(),
                          onChanged: (val) {
                            if (val != null) _onKeuskupanChanged(val);
                          },
                          emptyMessage: 'Keuskupan tidak ditemukan',
                        ),

                        // 2. Paroki
                        SearchableSelectField<int>(
                          label: 'Paroki',
                          icon: Icons.church_outlined,
                          value: _selectedParokiId,
                          enabled: !_isSameParish,
                          items: _parokiList
                              .map((item) => SearchableSelectItem<int>(
                                    value: int.parse(item['id'].toString()),
                                    label: item['name'].toString(),
                                  ))
                              .toList(),
                          onChanged: (val) {
                            if (val != null) setState(() => _selectedParokiId = val);
                          },
                          emptyMessage: 'Paroki tidak ditemukan pada keuskupan ini',
                        ),

                        // 3. Provinsi
                        SearchableSelectField<int>(
                          label: 'Provinsi',
                          icon: Icons.map_rounded,
                          value: _selectedProvinsiId,
                          enabled: !_isSameParish,
                          items: _provinsiList
                              .map((item) => SearchableSelectItem<int>(
                                    value: int.parse(item['id'].toString()),
                                    label: item['name'].toString(),
                                  ))
                              .toList(),
                          onChanged: (val) {
                            if (val != null) _onProvinsiChanged(val);
                          },
                          emptyMessage: 'Provinsi tidak ditemukan',
                        ),

                        // 4. Kota / Kabupaten
                        SearchableSelectField<int>(
                          label: 'Kota / Kabupaten',
                          icon: Icons.location_city_rounded,
                          value: _selectedKabupatenKotaId,
                          enabled: !_isSameParish,
                          items: _kabupatenKotaList
                              .map((item) => SearchableSelectItem<int>(
                                    value: int.parse(item['id'].toString()),
                                    label: item['name'].toString(),
                                  ))
                              .toList(),
                          onChanged: (val) {
                            if (val != null) setState(() => _selectedKabupatenKotaId = val);
                          },
                          emptyMessage: 'Kota tidak ditemukan pada provinsi ini',
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),

            // ── Sticky Bottom Action Bar ──
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.white,
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(0.06),
                    blurRadius: 10,
                    offset: const Offset(0, -4),
                  ),
                ],
              ),
              child: SafeArea(
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton(
                        onPressed: _isLoading ? null : _submit,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF1E5399),
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          elevation: 0,
                        ),
                        child: _isLoading
                            ? const SizedBox(
                                height: 20,
                                width: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  color: Colors.white,
                                ),
                              )
                            : const Text(
                                'KIRIM PELAYANAN',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.bold,
                                  letterSpacing: 0.5,
                                ),
                              ),
                      ),
                    ),
                    const SizedBox(height: 8),
                    SizedBox(
                      width: double.infinity,
                      child: OutlinedButton(
                        onPressed: () => Navigator.pop(context),
                        style: OutlinedButton.styleFrom(
                          foregroundColor: const Color(0xFFB91C1C),
                          backgroundColor: const Color(0xFFFEF2F2),
                          side: const BorderSide(color: Color(0xFFFECACA)),
                          padding: const EdgeInsets.symmetric(vertical: 14),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                        child: const Text(
                          'BATALKAN',
                          style: TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.bold,
                            letterSpacing: 0.5,
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildHeroHeader() {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.04),
            blurRadius: 12,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            height: 120,
            width: double.infinity,
            child: ClipRRect(
              borderRadius:
                  const BorderRadius.vertical(top: Radius.circular(20)),
              child: Stack(
                children: [
                  Positioned.fill(
                    child: Image.asset(
                      'assets/images/church_1.jpg',
                      fit: BoxFit.cover,
                    ),
                  ),
                  Positioned.fill(
                    child: Container(
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          colors: [
                            Colors.black.withOpacity(0.2),
                            Colors.black.withOpacity(0.75),
                          ],
                          begin: Alignment.topCenter,
                          end: Alignment.bottomCenter,
                        ),
                      ),
                    ),
                  ),
                  Positioned(
                    bottom: 12,
                    left: 16,
                    right: 16,
                    child: Row(
                      children: const [
                        Icon(Icons.personal_injury_rounded,
                            color: Colors.white, size: 24),
                        SizedBox(width: 10),
                        Expanded(
                          child: Text(
                            'Detail Pelayanan Misa Kedukaan',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 17,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
          ),
          const Padding(
            padding: EdgeInsets.all(14.0),
            child: Text(
              'Isi form dibawah ini sesuai permintaan pelayanan yang dibutuhkan',
              style: TextStyle(
                fontSize: 12.5,
                color: Color(0xFF64748B),
                height: 1.3,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFormCard({
    required String title,
    required IconData icon,
    required Color iconColor,
    required List<Widget> children,
  }) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFE2E8F0)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.02),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: iconColor.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Icon(icon, color: iconColor, size: 20),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: Text(
                  title,
                  style: const TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF0F172A),
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),
          ...children,
        ],
      ),
    );
  }

  Widget _buildInputField({
    required TextEditingController controller,
    String? label,
    String? hint,
    required IconData prefixIcon,
    Widget? suffixIcon,
    TextInputType keyboardType = TextInputType.text,
    List<TextInputFormatter>? inputFormatters,
    int maxLines = 1,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (label != null) ...[
          Text(
            label,
            style: const TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.bold,
              color: Color(0xFF334155),
            ),
          ),
          const SizedBox(height: 6),
        ],
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          inputFormatters: inputFormatters,
          maxLines: maxLines,
          style: const TextStyle(fontSize: 14, color: Color(0xFF0F172A)),
          decoration: InputDecoration(
            hintText: hint,
            hintStyle:
                TextStyle(color: Colors.grey.shade400, fontSize: 13.5),
            prefixIcon: Icon(prefixIcon,
                color: const Color(0xFF1E5399), size: 20),
            suffixIcon: suffixIcon,
            filled: true,
            fillColor: const Color(0xFFF8FAFC),
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFCBD5E1)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFCBD5E1)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide:
                  const BorderSide(color: Color(0xFF1E5399), width: 1.8),
            ),
            errorBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Colors.redAccent),
            ),
          ),
          validator: validator,
        ),
      ],
    );
  }

  Widget _buildDropdownField<T>({
    required T? value,
    required String label,
    required String hint,
    required IconData prefixIcon,
    required List<T> items,
    required String Function(T) itemLabel,
    required ValueChanged<T?>? onChanged,
    String? Function(T?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.bold,
            color: Color(0xFF334155),
          ),
        ),
        const SizedBox(height: 6),
        DropdownButtonFormField<T>(
          key: ValueKey('${label}_${value}_${items.length}'),
          value: value,
          decoration: InputDecoration(
            hintText: hint,
            hintStyle:
                TextStyle(color: Colors.grey.shade400, fontSize: 13.5),
            prefixIcon: Icon(prefixIcon,
                color: const Color(0xFF1E5399), size: 20),
            filled: true,
            fillColor: onChanged == null
                ? const Color(0xFFF1F5F9)
                : const Color(0xFFF8FAFC),
            contentPadding:
                const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFCBD5E1)),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide: const BorderSide(color: Color(0xFFCBD5E1)),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
              borderSide:
                  const BorderSide(color: Color(0xFF1E5399), width: 1.8),
            ),
          ),
          dropdownColor: Colors.white,
          borderRadius: BorderRadius.circular(12),
          isExpanded: true,
          items: items
              .map(
                (item) => DropdownMenuItem<T>(
                  value: item,
                  child: Text(
                    itemLabel(item),
                    style: const TextStyle(
                        fontSize: 13.5, color: Color(0xFF0F172A)),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              )
              .toList(),
          onChanged: onChanged,
          validator: validator,
        ),
      ],
    );
  }

  Widget _buildTimePickerTile({
    required String label,
    required String timeValue,
    required IconData prefixIcon,
    required VoidCallback onTap,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontSize: 13,
            fontWeight: FontWeight.bold,
            color: Color(0xFF334155),
          ),
        ),
        const SizedBox(height: 6),
        InkWell(
          onTap: onTap,
          borderRadius: BorderRadius.circular(12),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFC),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: const Color(0xFFCBD5E1)),
            ),
            child: Row(
              children: [
                Icon(prefixIcon, color: const Color(0xFF1E5399), size: 20),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    timeValue,
                    style: const TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w600,
                      color: Color(0xFF0F172A),
                    ),
                  ),
                ),
                const Icon(
                  Icons.arrow_drop_down_rounded,
                  color: Color(0xFF64748B),
                  size: 24,
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
