// Generated by Codex Agent

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../core/constants/app_constants.dart';
import '../../core/services/api_service.dart';

class CreatePerminyakanScreen extends StatefulWidget {
  const CreatePerminyakanScreen({super.key});

  @override
  State<CreatePerminyakanScreen> createState() =>
      _CreatePerminyakanScreenState();
}

class _CreatePerminyakanScreenState extends State<CreatePerminyakanScreen> {
  final _formKey = GlobalKey<FormState>();

  // Controllers
  final _namaController = TextEditingController();
  final _catatanController = TextEditingController();
  final _usiaController = TextEditingController(text: '0');
  final _tanggalController = TextEditingController();
  final _alamatController = TextEditingController();

  // Dropdowns
  String? _selectedUrgensi;
  String? _selectedGender;
  String? _jamMulai;
  String? _jamSelesai;

  bool _isLoading = false;

  static const _urgensiOptions = [
    'Standar',
    'Penting',
    'Sangat Penting / Butuh Segera',
  ];

  static const _genderOptions = ['Laki-laki', 'Perempuan'];

  // Generate jam options (00:00 - 23:30, step 30 menit)
  static List<String> get _jamOptions {
    final list = <String>[];
    for (int h = 0; h < 24; h++) {
      for (int m = 0; m < 60; m += 30) {
        list.add('${h.toString().padLeft(2, '0')}:${m.toString().padLeft(2, '0')}');
      }
    }
    return list;
  }

  @override
  void initState() {
    super.initState();
    // Default jam mulai = now, jam selesai = now + 2 jam
    final now = TimeOfDay.now();
    final hh = now.hour.toString().padLeft(2, '0');
    final mm = (now.minute < 30 ? 0 : 30).toString().padLeft(2, '0');
    _jamMulai = '$hh:$mm';
    final endHour = (now.hour + 2) % 24;
    _jamSelesai = '${endHour.toString().padLeft(2, '0')}:$mm';
  }

  @override
  void dispose() {
    _namaController.dispose();
    _catatanController.dispose();
    _usiaController.dispose();
    _tanggalController.dispose();
    _alamatController.dispose();
    super.dispose();
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
      builder: (ctx, child) => Theme(
        data: Theme.of(ctx).copyWith(
          colorScheme: const ColorScheme.light(primary: AppConstants.primaryBlue),
        ),
        child: child!,
      ),
    );
    if (picked != null) {
      setState(() {
        _tanggalController.text =
            '${picked.day.toString().padLeft(2, '0')}/${picked.month.toString().padLeft(2, '0')}/${picked.year}';
      });
    }
  }

  int _urgensiToId(String? label) {
    if (label == null) return 2;
    if (label.contains('Sangat')) return 3;
    if (label.contains('Penting')) return 2;
    return 1;
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    if (_tanggalController.text.isEmpty) {
      _showError('Tanggal pelayanan belum dipilih.');
      return;
    }
    if (_jamMulai == null || _jamSelesai == null) {
      _showError('Jam mulai dan selesai harus dipilih.');
      return;
    }

    setState(() => _isLoading = true);

    // Parse tanggal dari dd/MM/yyyy ke yyyy-MM-dd
    final parts = _tanggalController.text.split('/');
    final dateFormatted =
        parts.length == 3 ? '${parts[2]}-${parts[1]}-${parts[0]}' : _tanggalController.text;

    // Build notes dengan data sakramen
    final notes = [
      'Nama Penerima: ${_namaController.text}',
      'Gender: ${_selectedGender ?? '-'}',
      'Usia: ${_usiaController.text} tahun',
      'Jam Mulai: $_jamMulai',
      'Jam Selesai: $_jamSelesai',
      if (_catatanController.text.isNotEmpty) 'Catatan: ${_catatanController.text}',
    ].join(' | ');

    final res = await ApiService.createOrder(
      serviceCategoryId: 1, // Perminyakan Orang Sakit = id 1
      urgencyLevelId: _urgensiToId(_selectedUrgensi),
      scheduledDate: dateFormatted,
      scheduledTime: _jamMulai!,
      locationName: _alamatController.text,
      addressDetail: _alamatController.text,
      notes: notes,
    );

    setState(() => _isLoading = false);
    if (!mounted) return;

    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(res['message'] ?? 'Permintaan berhasil dikirim'),
        backgroundColor:
            res['message']?.toString().toLowerCase().contains('gagal') == true
                ? Colors.red
                : Colors.green.shade700,
      ),
    );

    if (res['message']?.toString().toLowerCase().contains('gagal') != true) {
      Navigator.pop(context);
    }
  }

  void _showError(String msg) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(msg), backgroundColor: Colors.red),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_rounded,
              color: AppConstants.textDark, size: 20),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'Buat Permintaan Pelayanan',
          style: TextStyle(
            color: AppConstants.textDark,
            fontSize: 17,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(20, 8, 20, 40),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Subtitle
              const Text(
                'Isi form dibawah ini sesuai permintaan pelayanan yang dibutuhkan',
                style: TextStyle(
                  fontSize: 14,
                  color: AppConstants.textMuted,
                  height: 1.4,
                ),
              ),
              const SizedBox(height: 22),

              // Section label
              const Text(
                'Sakramen Perminyakan',
                style: TextStyle(
                  fontSize: 15,
                  fontWeight: FontWeight.bold,
                  color: AppConstants.textDark,
                ),
              ),
              const SizedBox(height: 14),

              // 1. Nama Penerima
              _buildTextField(
                controller: _namaController,
                hint: 'Nama penerima Sakramen Perminyakan',
                validator: (v) =>
                    v == null || v.isEmpty ? 'Nama wajib diisi' : null,
              ),
              const SizedBox(height: 12),

              // 2. Jenis Urgensi
              _buildDropdown<String>(
                value: _selectedUrgensi,
                hint: 'Jenis Urgensi',
                items: _urgensiOptions,
                itemLabel: (e) => e,
                onChanged: (v) => setState(() => _selectedUrgensi = v),
                validator: (v) =>
                    v == null ? 'Jenis urgensi wajib dipilih' : null,
              ),
              const SizedBox(height: 12),

              // 3. Catatan
              _buildTextField(
                controller: _catatanController,
                hint: 'Catatan',
                maxLines: 3,
              ),
              const SizedBox(height: 12),

              // 4. Pilih Gender
              _buildDropdown<String>(
                value: _selectedGender,
                hint: 'Pilih Gender',
                items: _genderOptions,
                itemLabel: (e) => e,
                onChanged: (v) => setState(() => _selectedGender = v),
                validator: (v) => v == null ? 'Gender wajib dipilih' : null,
              ),
              const SizedBox(height: 12),

              // 5. Usia
              _buildTextField(
                controller: _usiaController,
                hint: 'Usia Penerima Sakramen Perminyakan',
                label: 'Usia Penerima Sakramen Perminyakan',
                keyboardType: TextInputType.number,
                inputFormatters: [FilteringTextInputFormatter.digitsOnly],
                validator: (v) =>
                    v == null || v.isEmpty ? 'Usia wajib diisi' : null,
              ),
              const SizedBox(height: 20),

              // Date section label
              const Text(
                'Pilih tanggal mulai pelayanan yang anda minta.',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.bold,
                  color: AppConstants.textDark,
                ),
              ),
              const SizedBox(height: 12),

              // 6. Tanggal Pelayanan
              GestureDetector(
                onTap: _pickDate,
                child: AbsorbPointer(
                  child: _buildTextField(
                    controller: _tanggalController,
                    hint: 'Tanggal Pelayanan',
                    suffixIcon: const Icon(Icons.calendar_today_outlined,
                        color: AppConstants.primaryBlue, size: 20),
                    validator: (v) =>
                        v == null || v.isEmpty ? 'Tanggal wajib dipilih' : null,
                  ),
                ),
              ),
              const SizedBox(height: 12),

              // 7. Jam Mulai & Jam Selesai (2 kolom)
              Row(
                children: [
                  Expanded(
                    child: _buildDropdown<String>(
                      value: _jamMulai,
                      hint: 'Jam Mulai',
                      label: 'Jam Mulai',
                      items: _jamOptions,
                      itemLabel: (e) => e,
                      onChanged: (v) => setState(() => _jamMulai = v),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: _buildDropdown<String>(
                      value: _jamSelesai,
                      hint: 'Jam Selesai',
                      label: 'Jam Selesai',
                      items: _jamOptions,
                      itemLabel: (e) => e,
                      onChanged: (v) => setState(() => _jamSelesai = v),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),

              // 8. Alamat Detail
              _buildTextField(
                controller: _alamatController,
                hint: 'Alamat Detail',
                maxLines: 3,
                validator: (v) =>
                    v == null || v.isEmpty ? 'Alamat wajib diisi' : null,
              ),
              const SizedBox(height: 32),

              // Submit Button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submit,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppConstants.primaryBlue,
                    disabledBackgroundColor:
                        AppConstants.primaryBlue.withOpacity(0.5),
                    padding: const EdgeInsets.symmetric(vertical: 16),
                    shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12)),
                    elevation: 2,
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          height: 22,
                          width: 22,
                          child: CircularProgressIndicator(
                              color: Colors.white, strokeWidth: 2.5),
                        )
                      : const Text(
                          'KIRIM PERMINTAAN PELAYANAN',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 15,
                            fontWeight: FontWeight.bold,
                            letterSpacing: 0.5,
                          ),
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ── Reusable Widgets ──

  Widget _buildTextField({
    required TextEditingController controller,
    required String hint,
    String? label,
    int maxLines = 1,
    TextInputType keyboardType = TextInputType.text,
    List<TextInputFormatter>? inputFormatters,
    Widget? suffixIcon,
    String? Function(String?)? validator,
  }) {
    return TextFormField(
      controller: controller,
      maxLines: maxLines,
      keyboardType: keyboardType,
      inputFormatters: inputFormatters,
      validator: validator,
      style: const TextStyle(fontSize: 15, color: AppConstants.textDark),
      decoration: InputDecoration(
        hintText: hint,
        labelText: label,
        hintStyle: const TextStyle(color: AppConstants.textMuted, fontSize: 14),
        labelStyle: const TextStyle(color: AppConstants.textMuted, fontSize: 13),
        suffixIcon: suffixIcon,
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide:
              const BorderSide(color: AppConstants.primaryBlue, width: 1.5),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide:
              const BorderSide(color: AppConstants.primaryBlue, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Colors.red, width: 1.5),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Colors.red, width: 2),
        ),
        filled: false,
      ),
    );
  }

  Widget _buildDropdown<T>({
    required T? value,
    required String hint,
    String? label,
    required List<T> items,
    required String Function(T) itemLabel,
    required void Function(T?) onChanged,
    String? Function(T?)? validator,
  }) {
    return DropdownButtonFormField<T>(
      value: value,
      validator: validator,
      isExpanded: true,
      icon: const Icon(Icons.keyboard_arrow_down_rounded,
          color: AppConstants.textMuted),
      style: const TextStyle(fontSize: 15, color: AppConstants.textDark),
      decoration: InputDecoration(
        hintText: label == null ? hint : null,
        labelText: label,
        hintStyle: const TextStyle(color: AppConstants.textDark, fontSize: 15),
        labelStyle: const TextStyle(color: AppConstants.textMuted, fontSize: 13),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide:
              const BorderSide(color: AppConstants.primaryBlue, width: 1.5),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide:
              const BorderSide(color: AppConstants.primaryBlue, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Colors.red, width: 1.5),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Colors.red, width: 2),
        ),
      ),
      hint: label == null
          ? Text(hint,
              style: const TextStyle(
                  color: AppConstants.textDark,
                  fontSize: 15,
                  fontWeight: FontWeight.normal))
          : null,
      items: items
          .map((e) => DropdownMenuItem<T>(
                value: e,
                child: Text(itemLabel(e),
                    style: const TextStyle(
                        fontSize: 14, color: AppConstants.textDark)),
              ))
          .toList(),
      onChanged: onChanged,
    );
  }
}
