// Generated by Codex Agent – Redesigned Modern UI
import 'dart:io';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import '../../core/constants/app_constants.dart';
import '../../core/models/models.dart';
import '../../core/services/language_service.dart';
import '../chat/chat_screen.dart';

class OrderDetailScreen extends StatefulWidget {
  final Order order;
  final String userName;
  final String? selectedItemTitle;

  const OrderDetailScreen({
    Key? key,
    required this.order,
    required this.userName,
    this.selectedItemTitle,
  }) : super(key: key);

  @override
  State<OrderDetailScreen> createState() => _OrderDetailScreenState();
}

class _OrderDetailScreenState extends State<OrderDetailScreen>
    with SingleTickerProviderStateMixin {
  late AnimationController _animController;
  late Animation<double> _fadeIn;
  late Animation<Offset> _slideUp;

  @override
  void initState() {
    super.initState();
    LanguageService.currentLanguage.addListener(_onLanguageChanged);
    _animController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 600),
    );
    _fadeIn = CurvedAnimation(parent: _animController, curve: Curves.easeOut);
    _slideUp = Tween<Offset>(
      begin: const Offset(0, 0.06),
      end: Offset.zero,
    ).animate(CurvedAnimation(parent: _animController, curve: Curves.easeOut));
    _animController.forward();
  }

  void _onLanguageChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    LanguageService.currentLanguage.removeListener(_onLanguageChanged);
    _animController.dispose();
    super.dispose();
  }

  // ── Status helpers ──────────────────────────────────────────────────────────

  Color _getStatusColor(String status) {
    switch (status.toUpperCase()) {
      case 'CONFIRMED':
        return const Color(0xFF0891B2);  // cyan
      case 'IN_PROGRESS':
        return const Color(0xFF7C3AED);  // ungu
      case 'DONE':
        return const Color(0xFF059669);  // hijau
      case 'CLOSE':
        return const Color(0xFF92400E);  // coklat
      case 'FAIL':
        return const Color(0xFFDC2626);  // merah
      case 'PENDING':
      default:
        return const Color(0xFFD97706);  // oranye
    }
  }

  String _getStatusLabel(String status) {
    switch (status.toUpperCase()) {
      case 'PENDING':
        return LanguageService.tr('status_pending');
      case 'CONFIRMED':
        return LanguageService.tr('status_confirmed');
      case 'IN_PROGRESS':
        return LanguageService.tr('status_in_progress');
      case 'DONE':
        return LanguageService.tr('status_done');
      case 'CLOSE':
        return LanguageService.tr('status_closed');
      case 'FAIL':
        return LanguageService.tr('status_failed');
      default:
        return LanguageService.tr('status_pending');
    }
  }

  IconData _getStatusIcon(String status) {
    switch (status.toUpperCase()) {
      case 'CONFIRMED':
        return Icons.how_to_reg_rounded;
      case 'IN_PROGRESS':
        return Icons.timelapse_rounded;
      case 'DONE':
        return Icons.check_circle_rounded;
      case 'CLOSE':
        return Icons.block_rounded;
      case 'FAIL':
        return Icons.cancel_rounded;
      case 'PENDING':
      default:
        return Icons.schedule_rounded;
    }
  }

  Color _getUrgencyColor(String urgency) {
    if (urgency.toLowerCase().contains('sangat')) return const Color(0xFFDC2626);
    if (urgency.toLowerCase().contains('penting')) return const Color(0xFFD97706);
    return const Color(0xFF1D4ED8);
  }

  // ── Hero backgrounds ────────────────────────────────────────────────────────

  Widget _buildHeroBackground(Order order, bool isKedukaan, Color urgencyColor) {
    if (isKedukaan) {
      return Stack(
        fit: StackFit.expand,
        children: [
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                colors: [Color(0xFF0D1117), Color(0xFF161B22), Color(0xFF0D1117)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
          ),
          // Ambient radial glow
          Center(
            child: Container(
              width: 200,
              height: 200,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                gradient: RadialGradient(
                  colors: [
                    const Color(0xFFD4AF37).withValues(alpha: 0.15),
                    Colors.transparent,
                  ],
                ),
              ),
            ),
          ),
          Positioned.fill(
            child: Padding(
              padding: const EdgeInsets.only(top: 56, bottom: 24),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  // Gold-framed portrait
                  Container(
                    width: 96,
                    height: 96,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      gradient: const LinearGradient(
                        colors: [Color(0xFFD4AF37), Color(0xFFF5D77D), Color(0xFFD4AF37)],
                        begin: Alignment.topLeft,
                        end: Alignment.bottomRight,
                      ),
                      boxShadow: [
                        BoxShadow(
                          color: const Color(0xFFD4AF37).withValues(alpha: 0.3),
                          blurRadius: 20,
                          spreadRadius: 4,
                        ),
                      ],
                    ),
                    child: Padding(
                      padding: const EdgeInsets.all(2.5),
                      child: ClipOval(
                        child: _buildDeceasedAvatarImage(order.attachmentUrl),
                      ),
                    ),
                  ),
                  const SizedBox(height: 14),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 24),
                    child: Text(
                      order.penerimaName,
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 22,
                        fontWeight: FontWeight.w700,
                        letterSpacing: -0.4,
                      ),
                      maxLines: 2,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                  const SizedBox(height: 10),
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      _buildMiniChip('MISA KEDUKAAN', const Color(0xFFD4AF37), dark: true),
                      const SizedBox(width: 8),
                      _buildMiniChip(
                          order.urgencyName.toUpperCase(), urgencyColor, dark: false),
                    ],
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Berpulang: ${order.tanggalMeninggalLabel}',
                    style: const TextStyle(
                      color: Color(0xFF8B949E),
                      fontSize: 12.5,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      );
    }

    // Default: church image bg
    return Stack(
      fit: StackFit.expand,
      children: [
        Image.asset('assets/images/church_1.jpg', fit: BoxFit.cover),
        Container(
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: [
                Colors.black.withValues(alpha: 0.15),
                Colors.black.withValues(alpha: 0.78),
              ],
              begin: Alignment.topCenter,
              end: Alignment.bottomCenter,
            ),
          ),
        ),
        Positioned(
          left: 20,
          right: 20,
          bottom: 28,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildMiniChip(order.urgencyName.toUpperCase(), urgencyColor, dark: false),
              const SizedBox(height: 10),
              Text(
                order.penerimaName,
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 26,
                  fontWeight: FontWeight.w800,
                  letterSpacing: -0.5,
                  height: 1.15,
                ),
              ),
              const SizedBox(height: 5),
              Row(
                children: [
                  const Icon(Icons.person_rounded, size: 14, color: Colors.white60),
                  const SizedBox(width: 5),
                  Text(
                    '${order.genderLabel.isNotEmpty ? order.genderLabel : 'Pria'} · ${order.usiaLabel.isNotEmpty ? order.usiaLabel : '-'}',
                    style: const TextStyle(
                      color: Colors.white70,
                      fontSize: 13,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildMiniChip(String label, Color color, {required bool dark}) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
      decoration: BoxDecoration(
        color: dark
            ? color.withValues(alpha: 0.18)
            : color.withValues(alpha: 0.9),
        borderRadius: BorderRadius.circular(8),
        border: dark
            ? Border.all(color: color.withValues(alpha: 0.5), width: 0.8)
            : null,
      ),
      child: Text(
        label,
        style: TextStyle(
          color: dark ? color : Colors.white,
          fontSize: 10,
          fontWeight: FontWeight.w900,
          letterSpacing: 0.7,
        ),
      ),
    );
  }

  // ── Avatar ──────────────────────────────────────────────────────────────────

  Widget _buildDeceasedAvatarImage(String? attachmentUrl) {
    if (attachmentUrl != null && attachmentUrl.isNotEmpty) {
      if (attachmentUrl.startsWith('data:image')) {
        try {
          final base64Content = attachmentUrl.split(',').last;
          final bytes = base64Decode(base64Content);
          return Image.memory(bytes, width: 92, height: 92, fit: BoxFit.cover,
              errorBuilder: (_, __, ___) => _defaultAvatar());
        } catch (_) {
          return _defaultAvatar();
        }
      } else if (attachmentUrl.startsWith('http://') ||
          attachmentUrl.startsWith('https://')) {
        return Image.network(attachmentUrl, width: 92, height: 92,
            fit: BoxFit.cover,
            errorBuilder: (_, __, ___) => _defaultAvatar());
      } else if (attachmentUrl.startsWith('assets/')) {
        return Image.asset(attachmentUrl, width: 92, height: 92,
            fit: BoxFit.cover,
            errorBuilder: (_, __, ___) => _defaultAvatar());
      } else {
        final file = File(attachmentUrl);
        if (file.existsSync()) {
          return Image.file(file, width: 92, height: 92, fit: BoxFit.cover,
              errorBuilder: (_, __, ___) => _defaultAvatar());
        }
      }
    }
    return _defaultAvatar();
  }

  Widget _defaultAvatar() {
    return Container(
      color: const Color(0xFF21262D),
      child: const Center(
        child: Icon(Icons.person_rounded, size: 44, color: Color(0xFF8B949E)),
      ),
    );
  }

  // ── Build ────────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    final order = widget.order;
    final statusColor = _getStatusColor(order.status);
    final statusLabel = _getStatusLabel(order.status);
    final statusIcon = _getStatusIcon(order.status);
    final urgencyColor = _getUrgencyColor(order.urgencyName);
    final bool isKedukaan =
        order.categoryName.toLowerCase().contains('kedukaan');

    OrderItem? targetItem;
    if (widget.selectedItemTitle != null && order.items.isNotEmpty) {
      for (final item in order.items) {
        if (item.itemName.toLowerCase().trim() ==
            widget.selectedItemTitle!.toLowerCase().trim()) {
          targetItem = item;
          break;
        }
      }
    }
    targetItem ??= (order.items.isNotEmpty ? order.items.first : null);

    final OrderItem displayItem = targetItem ??
        OrderItem(
          itemName: order.categoryName,
          scheduledDate: order.scheduledDate,
          scheduledTimeStart: order.jamMulaiLabel,
          scheduledTimeEnd:
              order.jamSelesaiLabel.isNotEmpty ? order.jamSelesaiLabel : 'Selesai',
          locationName: order.displayAddress,
        );

    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle.light,
      child: Scaffold(
        backgroundColor: const Color(0xFFF1F5F9),
        body: Stack(
          children: [
            FadeTransition(
              opacity: _fadeIn,
              child: SlideTransition(
                position: _slideUp,
                child: CustomScrollView(
                  physics: const BouncingScrollPhysics(),
                  slivers: [
                    // ── Hero AppBar ──
                    SliverAppBar(
                      expandedHeight: isKedukaan ? 320.0 : 290.0,
                      pinned: true,
                      backgroundColor: const Color(0xFF0D1117),
                      elevation: 0,
                      leading: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: GestureDetector(
                          onTap: () => Navigator.pop(context),
                          child: Container(
                            decoration: BoxDecoration(
                              color: Colors.black.withValues(alpha: 0.4),
                              shape: BoxShape.circle,
                              border: Border.all(
                                  color: Colors.white.withValues(alpha: 0.2),
                                  width: 1),
                            ),
                            child: const Icon(
                              Icons.arrow_back_ios_new_rounded,
                              color: Colors.white,
                              size: 16,
                            ),
                          ),
                        ),
                      ),
                      actions: [
                        Padding(
                          padding: const EdgeInsets.only(right: 16),
                          child: Center(
                            child: Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 12, vertical: 6),
                              decoration: BoxDecoration(
                                color: Colors.white.withValues(alpha: 0.15),
                                borderRadius: BorderRadius.circular(20),
                                border: Border.all(
                                    color: Colors.white.withValues(alpha: 0.25)),
                              ),
                              child: Text(
                                '#${order.orderNumber}',
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 12,
                                  fontWeight: FontWeight.w700,
                                  letterSpacing: 0.5,
                                ),
                              ),
                            ),
                          ),
                        ),
                      ],
                      flexibleSpace: FlexibleSpaceBar(
                        background:
                            _buildHeroBackground(order, isKedukaan, urgencyColor),
                      ),
                    ),

                    // ── Body ──
                    SliverToBoxAdapter(
                      child: Padding(
                        padding: const EdgeInsets.fromLTRB(16, 16, 16, 120),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            // ── Title + Status Chip ──
                            _buildTitleCard(
                                displayItem, order, statusColor, statusLabel, statusIcon),

                            const SizedBox(height: 12),

                            // ── Schedule & Location Card ──
                            _buildInfoCard(
                              icon: Icons.event_rounded,
                              iconBg: const Color(0xFF1D4ED8),
                              title: LanguageService.tr('time_location'),
                              children: [
                                _buildInfoTile(
                                  icon: Icons.calendar_month_rounded,
                                  label: 'Tanggal Misa',
                                  value: displayItem.scheduledDate,
                                ),
                                _buildInfoTile(
                                  icon: Icons.access_time_rounded,
                                  label: 'Jam Pelaksanaan',
                                  value:
                                      '${displayItem.scheduledTimeStart} – ${displayItem.scheduledTimeEnd} WIB',
                                ),
                                _buildInfoTile(
                                  icon: Icons.place_rounded,
                                  label: 'Lokasi',
                                  value: displayItem.locationName.isNotEmpty
                                      ? displayItem.locationName
                                      : order.displayAddress,
                                  isLast: true,
                                ),
                              ],
                            ),

                            const SizedBox(height: 12),

                            // ── Data Almarhum / Almarhumah (if kedukaan) ──
                            if (isKedukaan) ...[
                              _buildInfoCard(
                                icon: Icons.person_outline_rounded,
                                iconBg: const Color(0xFF7C3AED),
                                title: LanguageService.tr('deceased_data'),
                                children: [
                                  _buildInfoTile(
                                    icon: Icons.badge_rounded,
                                    label: LanguageService.tr('name_label'),
                                    value: order.penerimaName,
                                  ),
                                  _buildInfoTile(
                                    icon: Icons.favorite_border_rounded,
                                    label: 'Hubungan Pemohon',
                                    value: order.hubunganLabel,
                                  ),
                                  _buildInfoTile(
                                    icon: Icons.event_busy_rounded,
                                    label: 'Tanggal Meninggal',
                                    value: order.tanggalMeninggalLabel,
                                  ),
                                  _buildInfoTile(
                                    icon: Icons.schedule_rounded,
                                    label: 'Waktu Meninggal',
                                    value: '${order.waktuMeninggalLabel} WIB',
                                  ),
                                  _buildInfoTile(
                                    icon: Icons.priority_high_rounded,
                                    label: 'Tingkat Urgensi',
                                    value: order.urgencyName,
                                    valueColor: urgencyColor,
                                    isLast: true,
                                  ),
                                ],
                              ),
                              const SizedBox(height: 12),
                            ] else ...[
                              _buildInfoCard(
                                icon: Icons.person_outline_rounded,
                                iconBg: const Color(0xFF7C3AED),
                                title: LanguageService.tr('recipient_data'),
                                children: [
                                  _buildInfoTile(
                                    icon: Icons.badge_rounded,
                                    label: LanguageService.tr('name_label'),
                                    value: order.penerimaName,
                                  ),
                                  _buildInfoTile(
                                    icon: Icons.wc_rounded,
                                    label: 'Jenis Kelamin',
                                    value: order.genderLabel.isNotEmpty
                                        ? order.genderLabel
                                        : '-',
                                  ),
                                  _buildInfoTile(
                                    icon: Icons.cake_rounded,
                                    label: 'Usia',
                                    value: order.usiaLabel.isNotEmpty
                                        ? order.usiaLabel
                                        : '-',
                                    isLast: true,
                                  ),
                                ],
                              ),
                              const SizedBox(height: 12),
                            ],

                            // ── Paroki & Wilayah ──
                            _buildInfoCard(
                              icon: Icons.church_rounded,
                              iconBg: const Color(0xFF0D9488),
                              title: LanguageService.tr('parish_region'),
                              children: [
                                _buildInfoTile(
                                  icon: Icons.location_city_rounded,
                                  label: 'Keuskupan',
                                  value: order.keuskupanName,
                                ),
                                _buildInfoTile(
                                  icon: Icons.apartment_rounded,
                                  label: 'Paroki',
                                  value: order.parokiName,
                                  isLast: true,
                                ),
                              ],
                            ),

                            const SizedBox(height: 12),

                            // ── Catatan & Pemohon ──
                            _buildInfoCard(
                              icon: Icons.notes_rounded,
                              iconBg: const Color(0xFFD97706),
                              title: LanguageService.tr('notes_applicant'),
                              children: [
                                _buildInfoTile(
                                  icon: Icons.account_circle_outlined,
                                  label: 'Nama Pemohon',
                                  value: order.pemohonName,
                                ),
                                _buildInfoTile(
                                  icon: Icons.groups_rounded,
                                  label: 'Lingkungan',
                                  value: 'Lingkungan ${order.lingkunganName}',
                                  isLast: order.catatanLabel.isEmpty,
                                ),
                                if (order.catatanLabel.isNotEmpty)
                                  _buildNotesTile(order.catatanLabel),
                              ],
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),

            // ── Floating Action Bar ──
            Positioned(
              left: 16,
              right: 16,
              bottom: 24,
              child: _buildFloatingChatButton(order),
            ),
          ],
        ),
      ),
    );
  }

  // ── Title Card ──────────────────────────────────────────────────────────────

  Widget _buildTitleCard(OrderItem displayItem, Order order, Color statusColor,
      String statusLabel, IconData statusIcon) {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 16,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      displayItem.itemName,
                      style: const TextStyle(
                        fontSize: 21,
                        fontWeight: FontWeight.w800,
                        color: Color(0xFF0F172A),
                        letterSpacing: -0.5,
                        height: 1.2,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      order.categoryName,
                      style: const TextStyle(
                        fontSize: 13.5,
                        color: Color(0xFF64748B),
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 12),
              // Status badge
              Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 10, vertical: 7),
                decoration: BoxDecoration(
                  color: statusColor.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(statusIcon, size: 14, color: statusColor),
                    const SizedBox(width: 5),
                    Text(
                      statusLabel,
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.w700,
                        color: statusColor,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ── Info Card ───────────────────────────────────────────────────────────────

  Widget _buildInfoCard({
    required IconData icon,
    required Color iconBg,
    required String title,
    required List<Widget> children,
  }) {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 16,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Card header
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 16, 16, 12),
            child: Row(
              children: [
                Container(
                  width: 34,
                  height: 34,
                  decoration: BoxDecoration(
                    color: iconBg,
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: Icon(icon, size: 18, color: Colors.white),
                ),
                const SizedBox(width: 10),
                Text(
                  title,
                  style: const TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.w700,
                    color: Color(0xFF0F172A),
                    letterSpacing: -0.2,
                  ),
                ),
              ],
            ),
          ),
          const Divider(height: 1, color: Color(0xFFF1F5F9)),
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 4, 16, 8),
            child: Column(children: children),
          ),
        ],
      ),
    );
  }

  // ── Info Tile ───────────────────────────────────────────────────────────────

  Widget _buildInfoTile({
    required IconData icon,
    required String label,
    required String value,
    Color? valueColor,
    bool isLast = false,
  }) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 10),
          child: Row(
            children: [
              Icon(icon, size: 17, color: const Color(0xFF94A3B8)),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      label,
                      style: const TextStyle(
                        fontSize: 11.5,
                        color: Color(0xFF94A3B8),
                        fontWeight: FontWeight.w600,
                        letterSpacing: 0.2,
                      ),
                    ),
                    const SizedBox(height: 2),
                    Text(
                      value.isNotEmpty ? value : '-',
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w600,
                        color: valueColor ?? const Color(0xFF0F172A),
                        height: 1.3,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        if (!isLast)
          const Divider(height: 1, thickness: 1, color: Color(0xFFF8FAFC)),
      ],
    );
  }

  // ── Notes Tile ──────────────────────────────────────────────────────────────

  Widget _buildNotesTile(String note) {
    return Column(
      children: [
        const Divider(height: 1, thickness: 1, color: Color(0xFFF8FAFC)),
        Padding(
          padding: const EdgeInsets.symmetric(vertical: 12),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Icon(Icons.format_quote_rounded,
                  size: 17, color: Color(0xFF94A3B8)),
              const SizedBox(width: 10),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text(
                      'Catatan Tambahan',
                      style: TextStyle(
                        fontSize: 11.5,
                        color: Color(0xFF94A3B8),
                        fontWeight: FontWeight.w600,
                        letterSpacing: 0.2,
                      ),
                    ),
                    const SizedBox(height: 6),
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: const Color(0xFFF8FAFC),
                        borderRadius: BorderRadius.circular(10),
                        border: Border.all(color: const Color(0xFFE2E8F0)),
                      ),
                      child: Text(
                        '"$note"',
                        style: const TextStyle(
                          fontSize: 13.5,
                          fontStyle: FontStyle.italic,
                          color: Color(0xFF334155),
                          height: 1.5,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  // ── Floating Chat Button ─────────────────────────────────────────────────────

  Widget _buildFloatingChatButton(Order order) {
    return Container(
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(20),
        boxShadow: [
          BoxShadow(
            color: AppConstants.primaryBlue.withValues(alpha: 0.35),
            blurRadius: 20,
            offset: const Offset(0, 8),
          ),
        ],
      ),
      child: Material(
        color: AppConstants.primaryBlue,
        borderRadius: BorderRadius.circular(20),
        child: InkWell(
          borderRadius: BorderRadius.circular(20),
          onTap: () {
            HapticFeedback.lightImpact();
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => ChatScreen(
                  groupId: order.id,
                  orderNumber: order.orderNumber,
                  userName: widget.userName,
                ),
              ),
            );
          },
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  width: 36,
                  height: 36,
                  decoration: BoxDecoration(
                    color: Colors.white.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(10),
                  ),
                  child: const Icon(
                    Icons.chat_bubble_outline_rounded,
                    color: Colors.white,
                    size: 18,
                  ),
                ),
                const SizedBox(width: 12),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      LanguageService.tr('service_discussion'),
                      style: const TextStyle(
                        color: Colors.white,
                        fontSize: 15,
                        fontWeight: FontWeight.w700,
                        letterSpacing: -0.2,
                      ),
                    ),
                    const Text(
                      'Buka chat dengan Romo',
                      style: TextStyle(
                        color: Colors.white60,
                        fontSize: 11.5,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ],
                ),
                const Spacer(),
                const Icon(Icons.arrow_forward_ios_rounded,
                    color: Colors.white70, size: 14),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
