// Generated by Codex Agent
import 'dart:io';
import 'package:flutter/material.dart';
import '../../core/constants/app_constants.dart';
import '../../core/models/models.dart';
import '../chat/chat_screen.dart';

class OrderDetailScreen extends StatefulWidget {
  final Order order;
  final String userName;

  const OrderDetailScreen({
    Key? key,
    required this.order,
    required this.userName,
  }) : super(key: key);

  @override
  State<OrderDetailScreen> createState() => _OrderDetailScreenState();
}

class _OrderDetailScreenState extends State<OrderDetailScreen> {
  bool _isDetailExpanded = true;

  Color _getStatusColor(String status) {
    switch (status.toUpperCase()) {
      case 'ACCEPTED':
      case 'SELESAI':
      case 'CONFIRMED':
        return const Color(0xFF10B981);
      case 'REJECTED':
      case 'DITOLAK':
      case 'CANCELLED':
        return const Color(0xFFEF4444);
      case 'IN_PROGRESS':
      case 'DIPROSES':
        return const Color(0xFF3B82F6);
      default:
        return const Color(0xFFF59E0B);
    }
  }

  String _getStatusLabel(String status) {
    switch (status.toUpperCase()) {
      case 'ACCEPTED':
      case 'CONFIRMED':
        return 'Disetujui';
      case 'SELESAI':
        return 'Selesai';
      case 'REJECTED':
      case 'DITOLAK':
        return 'Ditolak';
      case 'IN_PROGRESS':
      case 'DIPROSES':
        return 'Sedang Diproses';
      default:
        return 'Menunggu Konfirmasi';
    }
  }

  Color _getUrgencyColor(String urgency) {
    if (urgency.toLowerCase().contains('sangat')) return const Color(0xFFEF4444);
    if (urgency.toLowerCase().contains('penting')) return const Color(0xFFF59E0B);
    return const Color(0xFF1E5399);
  }

  Widget _buildDeceasedThumbnail(String? attachmentUrl) {
    if (attachmentUrl != null && attachmentUrl.isNotEmpty) {
      if (attachmentUrl.startsWith('http://') || attachmentUrl.startsWith('https://')) {
        return Image.network(
          attachmentUrl,
          width: 76,
          height: 76,
          fit: BoxFit.cover,
          errorBuilder: (_, __, ___) => _buildFallbackAvatar(),
        );
      }
      final file = File(attachmentUrl);
      if (file.existsSync()) {
        return Image.file(
          file,
          width: 76,
          height: 76,
          fit: BoxFit.cover,
          errorBuilder: (_, __, ___) => _buildFallbackAvatar(),
        );
      }
    }
    return _buildFallbackAvatar();
  }

  Widget _buildFallbackAvatar() {
    return Image.asset(
      'assets/images/church_1.jpg',
      width: 76,
      height: 76,
      fit: BoxFit.cover,
    );
  }

  @override
  Widget build(BuildContext context) {
    final order = widget.order;
    final statusColor = _getStatusColor(order.status);
    final statusLabel = _getStatusLabel(order.status);
    final urgencyColor = _getUrgencyColor(order.urgencyName);

    final String displayTitle = order.items.isNotEmpty
        ? order.items.first.itemName
        : (order.categoryName == 'Misa Kedukaan'
            ? 'Misa Requiem / Misa Arwah'
            : order.categoryName);

    return Scaffold(
      backgroundColor: Colors.white,
      body: Stack(
        children: [
          CustomScrollView(
            slivers: [
              // ── 1. Hero Header Banner ──
              SliverAppBar(
                expandedHeight: 250.0,
                pinned: true,
                backgroundColor: const Color(0xFF0F172A),
                elevation: 0,
                leading: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: GestureDetector(
                    onTap: () => Navigator.pop(context),
                    child: Container(
                      decoration: BoxDecoration(
                        color: Colors.black.withValues(alpha: 0.35),
                        shape: BoxShape.circle,
                        border: Border.all(
                            color: Colors.white.withValues(alpha: 0.2), width: 1),
                      ),
                      child: const Icon(
                        Icons.arrow_back_ios_new_rounded,
                        color: Colors.white,
                        size: 16,
                      ),
                    ),
                  ),
                ),
                actions: [
                  Padding(
                    padding: const EdgeInsets.only(right: 16),
                    child: Center(
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 12, vertical: 6),
                        decoration: BoxDecoration(
                          color: Colors.white.withValues(alpha: 0.2),
                          borderRadius: BorderRadius.circular(20),
                          border: Border.all(
                              color: Colors.white.withValues(alpha: 0.3)),
                        ),
                        child: Text(
                          '#${order.orderNumber}',
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 12,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
                flexibleSpace: FlexibleSpaceBar(
                  background: Stack(
                    fit: StackFit.expand,
                    children: [
                      Image.asset(
                        'assets/images/church_1.jpg',
                        fit: BoxFit.cover,
                      ),
                      Container(
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            colors: [
                              Colors.black.withValues(alpha: 0.2),
                              Colors.black.withValues(alpha: 0.85),
                            ],
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 20,
                        right: 20,
                        bottom: 20,
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 10, vertical: 4),
                              decoration: BoxDecoration(
                                color: urgencyColor,
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Text(
                                order.urgencyName.toUpperCase(),
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 10,
                                  fontWeight: FontWeight.w900,
                                  letterSpacing: 0.8,
                                ),
                              ),
                            ),
                            const SizedBox(height: 8),
                            Text(
                              displayTitle,
                              style: const TextStyle(
                                color: Colors.white,
                                fontSize: 24,
                                fontWeight: FontWeight.bold,
                                letterSpacing: -0.5,
                              ),
                            ),
                            const SizedBox(height: 4),
                            Text(
                              order.categoryName,
                              style: const TextStyle(
                                color: Colors.white70,
                                fontSize: 13,
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),

              // ── 2. Seamless Body Surface ──
              SliverToBoxAdapter(
                child: Container(
                  decoration: const BoxDecoration(
                    color: Colors.white,
                    borderRadius:
                        BorderRadius.vertical(top: Radius.circular(28)),
                  ),
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(20, 20, 20, 110),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        // ── Main Header Info Block (Matching Reference Image) ──
                        Text(
                          displayTitle,
                          style: const TextStyle(
                            fontSize: 22,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF0F172A),
                            letterSpacing: -0.3,
                          ),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          order.categoryName,
                          style: const TextStyle(
                            fontSize: 14,
                            color: Color(0xFF64748B),
                            fontWeight: FontWeight.w500,
                          ),
                        ),
                        const SizedBox(height: 12),

                        // Info Row 1: Tingkat Urgensi
                        Row(
                          children: [
                            const Icon(Icons.shopping_bag_outlined,
                                size: 18, color: Color(0xFFEF4444)),
                            const SizedBox(width: 10),
                            Text(
                              order.urgencyName,
                              style: const TextStyle(
                                fontSize: 14,
                                fontWeight: FontWeight.bold,
                                color: Color(0xFF0F172A),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),

                        // Info Row 2: Tanggal & Jam Pelayanan
                        Row(
                          children: [
                            const Icon(Icons.calendar_today_outlined,
                                size: 18, color: Color(0xFF1E5399)),
                            const SizedBox(width: 10),
                            Expanded(
                              child: Text(
                                order.jamSelesaiLabel.isNotEmpty
                                    ? '${order.scheduledDate} ${order.jamMulaiLabel} - ${order.jamSelesaiLabel}'
                                    : order.fullScheduleLabel,
                                style: const TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                  color: Color(0xFF0F172A),
                                ),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),

                        // Info Row 3: Rumah Kedukaan / Lokasi
                        Row(
                          children: [
                            const Icon(Icons.location_on_outlined,
                                size: 18, color: Color(0xFF0D9488)),
                            const SizedBox(width: 10),
                            Expanded(
                              child: Text(
                                order.displayAddress,
                                style: const TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                  color: Color(0xFF0F172A),
                                ),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 14),

                        // Status Badge Pill
                        Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.all(6),
                              decoration: BoxDecoration(
                                color: statusColor.withValues(alpha: 0.12),
                                borderRadius: BorderRadius.circular(8),
                              ),
                              child: Icon(
                                Icons.hourglass_top_rounded,
                                color: statusColor,
                                size: 18,
                              ),
                            ),
                            const SizedBox(width: 10),
                            Text(
                              statusLabel,
                              style: TextStyle(
                                fontSize: 15,
                                fontWeight: FontWeight.bold,
                                color: statusColor,
                              ),
                            ),
                          ],
                        ),

                        const SizedBox(height: 20),

                        // ── Expandable Detail Section Accordion ──
                        InkWell(
                          onTap: () {
                            setState(() {
                              _isDetailExpanded = !_isDetailExpanded;
                            });
                          },
                          splashColor: Colors.transparent,
                          highlightColor: Colors.transparent,
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              const Text(
                                'Detail',
                                style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.bold,
                                  color: Color(0xFF0F172A),
                                ),
                              ),
                              Icon(
                                _isDetailExpanded
                                    ? Icons.keyboard_arrow_up_rounded
                                    : Icons.keyboard_arrow_down_rounded,
                                color: const Color(0xFF0F172A),
                                size: 26,
                              ),
                            ],
                          ),
                        ),

                        if (_isDetailExpanded) ...[
                          const SizedBox(height: 8),

                          // Catatan tambahan (e.g. Meninggal karena ibadah)
                          if (order.catatanLabel.isNotEmpty) ...[
                            Text(
                              order.catatanLabel,
                              style: const TextStyle(
                                fontSize: 14,
                                color: Color(0xFF334155),
                                height: 1.4,
                              ),
                            ),
                            const SizedBox(height: 14),
                          ],

                          // Foto Almarhum + Table Key-Value Pair (2 Columns)
                          Row(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              // Left: Foto Almarhum Avatar Box
                              ClipRRect(
                                borderRadius: BorderRadius.circular(12),
                                child: Container(
                                  width: 76,
                                  height: 76,
                                  decoration: BoxDecoration(
                                    color: Colors.grey.shade200,
                                    borderRadius: BorderRadius.circular(12),
                                    border: Border.all(
                                      color: const Color(0xFFE2E8F0),
                                    ),
                                  ),
                                  child: _buildDeceasedThumbnail(
                                      order.attachmentUrl),
                                ),
                              ),
                              const SizedBox(width: 16),

                              // Right: Key-Value Table Details
                              Expanded(
                                child: Column(
                                  children: [
                                    _buildDetailPairRow(
                                      label: 'Hubungan',
                                      value: order.hubunganLabel,
                                    ),
                                    _buildDetailPairRow(
                                      label: 'Nama',
                                      value: order.penerimaName,
                                    ),
                                    _buildDetailPairRow(
                                      label: 'Rumah Kedukaan',
                                      value: order.displayAddress,
                                    ),
                                    _buildDetailPairRow(
                                      label: 'Tanggal meninggal',
                                      value: order.tanggalMeninggalLabel,
                                    ),
                                    _buildDetailPairRow(
                                      label: 'Waktu Meninggal',
                                      value: order.waktuMeninggalLabel,
                                    ),
                                    _buildDetailPairRow(
                                      label: 'Keuskupan',
                                      value: order.keuskupanName,
                                    ),
                                    _buildDetailPairRow(
                                      label: 'Paroki',
                                      value: order.parokiName,
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ],

                        const SizedBox(height: 24),
                        const Divider(height: 1, color: Color(0xFFF1F5F9)),
                        const SizedBox(height: 20),

                        // ── Multi-Item Misa Sessions Stepper (If Any) ──
                        if (order.items.isNotEmpty) ...[
                          _buildSectionHeader(
                            title: 'Daftar Misa Kedukaan (${order.items.length} Sesi)',
                            icon: Icons.church_outlined,
                          ),
                          const SizedBox(height: 16),
                          for (int i = 0; i < order.items.length; i++) ...[
                            _buildTimelineNode(
                              icon: Icons.church_rounded,
                              iconColor: const Color(0xFF1E5399),
                              title: order.items[i].itemName,
                              subtitle:
                                  '📅 ${order.items[i].scheduledDate} (${order.items[i].scheduledTimeStart} - ${order.items[i].scheduledTimeEnd} WIB)\n📍 ${order.items[i].locationName}',
                              isLast: i == order.items.length - 1,
                            ),
                          ],
                          const SizedBox(height: 20),
                          const Divider(height: 1, color: Color(0xFFF1F5F9)),
                          const SizedBox(height: 20),
                        ],

                        // ── Bottom Requester Profile Section (Matching Screenshot) ──
                        Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.all(10),
                              decoration: BoxDecoration(
                                color: const Color(0xFFF1F5F9),
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: const Icon(
                                Icons.person_outline_rounded,
                                color: Color(0xFF0F172A),
                                size: 28,
                              ),
                            ),
                            const SizedBox(width: 14),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    order.pemohonName,
                                    style: const TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.bold,
                                      color: Color(0xFF0F172A),
                                    ),
                                  ),
                                  const SizedBox(height: 2),
                                  Text(
                                    'Umat Dari Lingkungan ${order.lingkunganName}',
                                    style: const TextStyle(
                                      fontSize: 13,
                                      color: Color(0xFF64748B),
                                      fontWeight: FontWeight.w500,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
              ),
            ],
          ),

          // ── Floating Chat Action Button ──
          Positioned(
            left: 16,
            right: 16,
            bottom: 16,
            child: Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(24),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withValues(alpha: 0.12),
                    blurRadius: 24,
                    offset: const Offset(0, 8),
                  ),
                ],
              ),
              child: ElevatedButton.icon(
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => ChatScreen(
                        groupId: order.id,
                        orderNumber: order.orderNumber,
                        userName: widget.userName,
                      ),
                    ),
                  );
                },
                icon: const Icon(Icons.chat_bubble_outline_rounded, size: 20),
                label: const Text(
                  'Buka Diskusi / Chat Pelayanan',
                  style: TextStyle(
                    fontSize: 15,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppConstants.primaryBlue,
                  foregroundColor: Colors.white,
                  minimumSize: const Size(double.infinity, 52),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(20),
                  ),
                  elevation: 0,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionHeader({required String title, required IconData icon}) {
    return Row(
      children: [
        Icon(icon, size: 18, color: const Color(0xFF1E5399)),
        const SizedBox(width: 8),
        Text(
          title,
          style: const TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.bold,
            color: Color(0xFF0F172A),
          ),
        ),
      ],
    );
  }

  Widget _buildDetailPairRow({required String label, required String value}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 120,
            child: Text(
              label,
              style: const TextStyle(
                fontSize: 13,
                color: Color(0xFF475569),
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value.isNotEmpty ? value : '-',
              style: const TextStyle(
                fontSize: 13,
                color: Color(0xFF0F172A),
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTimelineNode({
    required IconData icon,
    required Color iconColor,
    required String title,
    required String subtitle,
    required bool isLast,
  }) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Column(
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: iconColor.withValues(alpha: 0.12),
                shape: BoxShape.circle,
              ),
              child: Icon(icon, size: 16, color: iconColor),
            ),
            if (!isLast)
              Container(
                width: 2,
                height: 38,
                color: const Color(0xFFE2E8F0),
              ),
          ],
        ),
        const SizedBox(width: 14),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                title,
                style: const TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF0F172A),
                ),
              ),
              const SizedBox(height: 3),
              Text(
                subtitle,
                style: const TextStyle(
                  fontSize: 12.5,
                  color: Color(0xFF64748B),
                  height: 1.4,
                ),
              ),
              const SizedBox(height: 16),
            ],
          ),
        ),
      ],
    );
  }
}
