// Generated by Codex Agent

import 'package:flutter/material.dart';
import '../../core/models/models.dart';
import '../../core/services/api_service.dart';
import '../../core/utils/fade_slide_route.dart';
import '../auth/login_screen.dart';
import 'romo_dashboard_view.dart';
import 'umat_dashboard_view.dart';

class HomeScreen extends StatefulWidget {
  final Map<String, dynamic> user;
  const HomeScreen({Key? key, required this.user}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  List<Order> _orders = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadOrders();
  }

  Future<void> _loadOrders() async {
    setState(() => _isLoading = true);
    final orders = await ApiService.getOrders();
    setState(() {
      _orders = orders;
      _isLoading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    final u = widget.user;
    final String roleCode = u['roleCode'] ?? u['role_code'] ?? u['role'] ?? 'UMAT';

    if (_isLoading) {
      return const Scaffold(
        body: Center(child: CircularProgressIndicator()),
      );
    }

    if (roleCode.startsWith('ROMO')) {
      return RomoDashboardView(
        user: u,
        orders: _orders,
        onRefresh: _loadOrders,
        onLogout: () {
          Navigator.pushReplacement(
            context,
            FadeSlideRoute(page: const LoginScreen()),
          );
        },
      );
    }

    // UMAT / PENGURUS_LINGKUNGAN / KOORDINATOR_KEUSKUPAN → Umat Dashboard
    return UmatDashboardView(
      user: u,
      orders: _orders,
      onRefresh: _loadOrders,
      onLogout: () {
        Navigator.pushReplacement(
          context,
          FadeSlideRoute(page: const LoginScreen()),
        );
      },
    );
  }
}
