// Generated by Codex Agent

import 'package:flutter/material.dart';
import '../../core/models/models.dart';
import '../../core/services/language_service.dart';
import '../../core/widgets/liquid_bottom_nav_bar.dart';
import '../orders/create_perminyakan_screen.dart';
import '../orders/create_kedukaan_screen.dart';
import '../orders/order_detail_screen.dart';
import '../orders/histori_screen.dart';
import '../orders/schedule_screen.dart';
import '../profile/main_menu_screen.dart';

List<LiquidNavItem> _buildNavItems() => [
      LiquidNavItem(
        icon: Icons.home_outlined,
        activeIcon: Icons.home_rounded,
        label: LanguageService.tr('nav_home'),
      ),
      LiquidNavItem(
        icon: Icons.history_outlined,
        activeIcon: Icons.history_rounded,
        label: LanguageService.tr('nav_history'),
      ),
      LiquidNavItem(
        icon: Icons.calendar_today_outlined,
        activeIcon: Icons.calendar_today_rounded,
        label: LanguageService.tr('nav_schedule'),
      ),
      LiquidNavItem(
        icon: Icons.menu_outlined,
        activeIcon: Icons.menu_rounded,
        label: LanguageService.tr('nav_profile'),
      ),
    ];

class UmatDashboardView extends StatefulWidget {
  final Map<String, dynamic> user;
  final List<Order> orders;
  final VoidCallback onRefresh;
  final VoidCallback onLogout;

  const UmatDashboardView({
    Key? key,
    required this.user,
    required this.orders,
    required this.onRefresh,
    required this.onLogout,
  }) : super(key: key);

  @override
  State<UmatDashboardView> createState() => _UmatDashboardViewState();
}

class _UmatDashboardViewState extends State<UmatDashboardView> {
  int _currentNavIndex = 0;

  @override
  void initState() {
    super.initState();
    LanguageService.currentLanguage.addListener(_onLanguageChanged);
  }

  void _onLanguageChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    LanguageService.currentLanguage.removeListener(_onLanguageChanged);
    super.dispose();
  }

  int? get _userId {
    final raw = widget.user['id'] ?? widget.user['userId'] ?? widget.user['user_id'];
    return raw != null ? int.tryParse(raw.toString()) : null;
  }

  @override
  Widget build(BuildContext context) {
    final String userName =
        widget.user['fullName'] ?? widget.user['full_name'] ?? 'Umat';
    final String pengurusPos =
        widget.user['pengurusPosition'] ?? widget.user['pengurus_position'] ?? '';
    final String? startDate =
        widget.user['jabatanStartDate'] ?? widget.user['jabatan_start_date'];
    final String? endDate =
        widget.user['jabatanEndDate'] ?? widget.user['jabatan_end_date'];
    final int? startYear =
        widget.user['jabatanStartYear'] ?? widget.user['jabatan_start_year'];
    final int? endYear =
        widget.user['jabatanEndYear'] ?? widget.user['jabatan_end_year'];
    final String accountStatus =
        widget.user['accountStatus'] ?? widget.user['account_status'] ?? 'PENDING';
    final bool isApproved = accountStatus == 'APPROVED';

    String positionTitle = 'Umat (Anggota)';
    if (pengurusPos == 'KETUA') positionTitle = 'Umat — Ketua Lingkungan';
    if (pengurusPos == 'WAKIL') positionTitle = 'Umat — Wakil Ketua';
    if (pengurusPos == 'SEKRETARIS') positionTitle = 'Umat — Sekretaris';

    final String periodeText =
        (startDate != null && endDate != null && startDate.isNotEmpty && endDate.isNotEmpty)
            ? '$startDate - $endDate'
            : (startYear != null && endYear != null ? '$startYear - $endYear' : '');

    // ── Histori Tab ──
    if (_currentNavIndex == 1) {
      return Scaffold(
        backgroundColor: const Color(0xFFF1F5F9),
        body: HistoriScreen(
          orders: widget.orders,
          userName: userName,
          onRefresh: widget.onRefresh,
        ),
        bottomNavigationBar: LiquidBottomNavBar(
          selectedIndex: _currentNavIndex,
          onTabSelected: (index) {
            setState(() => _currentNavIndex = index);
          },
          items: _buildNavItems(),
        ),
      );
    }

    // ── Jadwal / Schedule Tab ──
    if (_currentNavIndex == 2) {
      return Scaffold(
        backgroundColor: const Color(0xFFF1F5F9),
        body: ScheduleScreen(
          orders: widget.orders,
          userName: userName,
          onRefresh: widget.onRefresh,
        ),
        bottomNavigationBar: LiquidBottomNavBar(
          selectedIndex: _currentNavIndex,
          onTabSelected: (index) {
            setState(() => _currentNavIndex = index);
          },
          items: _buildNavItems(),
        ),
      );
    }

    // ── Menu Utama Tab ──
    if (_currentNavIndex == 3) {
      return Scaffold(
        backgroundColor: const Color(0xFFF1F5F9),
        body: MainMenuScreen(
          user: widget.user,
          onRefresh: widget.onRefresh,
          onLogout: widget.onLogout,
        ),
        bottomNavigationBar: LiquidBottomNavBar(
          selectedIndex: _currentNavIndex,
          onTabSelected: (index) {
            setState(() => _currentNavIndex = index);
          },
          items: _buildNavItems(),
        ),
      );
    }

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      body: SafeArea(
        child: Column(
          children: [
            // ── 1. Top Header Bar ──
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 8, 20, 6),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Hi, $userName',
                          style: const TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF0F172A),
                            letterSpacing: -0.3,
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                        const SizedBox(height: 3),
                        Row(
                          children: [
                            Text(
                              positionTitle,
                              style: const TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.bold,
                                color: Color(0xFF1E5399),
                              ),
                            ),
                            const SizedBox(width: 6),
                            Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 5, vertical: 1.5),
                              decoration: BoxDecoration(
                                color: isApproved
                                    ? Colors.green.shade600
                                    : const Color(0xFFD97706),
                                borderRadius: BorderRadius.circular(5),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(
                                    isApproved
                                        ? Icons.check_circle_rounded
                                        : Icons.hourglass_top_rounded,
                                    size: 9.5,
                                    color: Colors.white,
                                  ),
                                  const SizedBox(width: 3),
                                  Text(
                                    isApproved
                                        ? 'Disetujui'
                                        : 'Menunggu Verifikasi',
                                    style: const TextStyle(
                                      color: Colors.white,
                                      fontSize: 8.5,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                        if (startDate != null &&
                            endDate != null &&
                            startDate.isNotEmpty &&
                            endDate.isNotEmpty) ...[
                          const SizedBox(height: 3),
                          Row(
                            children: [
                              Text(
                                'Mulai: $startDate',
                                style: const TextStyle(
                                    fontSize: 10.5,
                                    fontWeight: FontWeight.w500,
                                    color: Color(0xFF64748B)),
                              ),
                              const SizedBox(width: 10),
                              Text(
                                'Selesai: $endDate',
                                style: const TextStyle(
                                    fontSize: 10.5,
                                    fontWeight: FontWeight.w500,
                                    color: Color(0xFF64748B)),
                              ),
                            ],
                          ),
                        ] else if (periodeText.isNotEmpty) ...[
                          const SizedBox(height: 2),
                          Text(
                            'Masa Bakti: $periodeText',
                            style: const TextStyle(
                                fontSize: 10.5, color: Color(0xFF64748B)),
                          ),
                        ],
                      ],
                    ),
                  ),
                  Row(
                    children: [
                      Stack(
                        clipBehavior: Clip.none,
                        children: [
                          IconButton(
                            icon: const Icon(Icons.notifications_none_rounded,
                                color: Color(0xFF1E5399), size: 26),
                            onPressed: () {},
                          ),
                          Positioned(
                            top: 6,
                            right: 6,
                            child: Container(
                              padding: const EdgeInsets.all(4),
                              decoration: const BoxDecoration(
                                color: Colors.redAccent,
                                shape: BoxShape.circle,
                              ),
                              constraints: const BoxConstraints(
                                  minWidth: 15, minHeight: 15),
                              child: const Text(
                                '1',
                                style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 9.5,
                                    fontWeight: FontWeight.bold),
                                textAlign: TextAlign.center,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(width: 4),
                      Stack(
                        clipBehavior: Clip.none,
                        children: [
                          IconButton(
                            icon: const Icon(Icons.mail_outline_rounded,
                                color: Color(0xFF1E5399), size: 26),
                            onPressed: () {},
                          ),
                          Positioned(
                            top: 6,
                            right: 6,
                            child: Container(
                              padding: const EdgeInsets.all(4),
                              decoration: const BoxDecoration(
                                color: Colors.redAccent,
                                shape: BoxShape.circle,
                              ),
                              constraints: const BoxConstraints(
                                  minWidth: 15, minHeight: 15),
                              child: const Text(
                                '2',
                                style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 9.5,
                                    fontWeight: FontWeight.bold),
                                textAlign: TextAlign.center,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ),

            // ── 2. Scrollable Body ──
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.only(bottom: 32),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Cross Banner
                    Padding(
                      padding: const EdgeInsets.fromLTRB(20, 8, 20, 0),
                      child: Container(
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(22),
                          boxShadow: [
                            BoxShadow(
                              color: const Color(0xFF1E5399).withOpacity(0.18),
                              blurRadius: 24,
                              spreadRadius: 2,
                              offset: const Offset(0, 8),
                            ),
                            BoxShadow(
                              color: Colors.black.withOpacity(0.08),
                              blurRadius: 10,
                              offset: const Offset(0, 4),
                            ),
                          ],
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(22),
                          child: AspectRatio(
                            aspectRatio: 16 / 9,
                            child: Image.asset(
                              'assets/images/cross_banner.jpg',
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ),

                    // ── 3. Spiritual Quote ──
                    Padding(
                      padding: const EdgeInsets.fromLTRB(28, 16, 28, 20),
                      child: Column(
                        children: const [
                          Text(
                            '" Sungguh, Allah itu keselamatanku; aku percaya dengan tidak gementar, sebab Tuhan Allah itu kekuatanku dan mazmurku, Ia telah menjadi keselamatanku. "',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 13,
                              fontStyle: FontStyle.italic,
                              color: Color(0xFF334155),
                              height: 1.4,
                            ),
                          ),
                          SizedBox(height: 6),
                          Text(
                            '- Yesaya 12:2 -',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                              color: Color(0xFF64748B),
                            ),
                          ),
                        ],
                      ),
                    ),

                    // ── 4. Daftar Permintaan Pelayanan ──
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 20),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          SizedBox(
                            width: 180,
                            child: Text(
                              LanguageService.tr('recent_orders'),
                              style: const TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.bold,
                                color: Color(0xFF0F172A),
                                height: 1.2,
                              ),
                            ),
                          ),
                          ElevatedButton(
                            onPressed: _showServiceSelectionModal,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: const Color(0xFF1E5399),
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 14, vertical: 10),
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(14)),
                              elevation: 0,
                            ),
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                const Icon(Icons.add_rounded, size: 16),
                                const SizedBox(width: 5),
                                Text(
                                  LanguageService.tr('quick_services'),
                                  style: const TextStyle(
                                      fontSize: 11,
                                      fontWeight: FontWeight.w600),
                                  textAlign: TextAlign.center,
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),

                    const SizedBox(height: 14),

                    // Horizontal Cards
                    SizedBox(
                      height: 250,
                      child: _displayCardItems.isEmpty
                          ? Padding(
                              padding:
                                  const EdgeInsets.symmetric(horizontal: 20),
                              child: Center(
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Icon(Icons.event_available_rounded,
                                        size: 48,
                                        color: Colors.grey.shade300),
                                    const SizedBox(height: 8),
                                    Text(
                                      'Tidak ada jadwal pelayanan aktif saat ini.\nJadwal terdahulu dapat dilihat di tab Histori.',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          color: Colors.grey.shade500,
                                          fontSize: 13),
                                    ),
                                  ],
                                ),
                              ),
                            )
                          : ListView.builder(
                              scrollDirection: Axis.horizontal,
                              padding:
                                  const EdgeInsets.symmetric(horizontal: 20),
                              itemCount: _displayCardItems.length,
                              itemBuilder: (context, index) {
                                final item = _displayCardItems[index];
                                return Padding(
                                  padding: const EdgeInsets.only(right: 14),
                                  child: GestureDetector(
                                    onTap: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                          builder: (_) => OrderDetailScreen(
                                            order: item.parentOrder,
                                            userName: userName,
                                            selectedItemTitle: item.title,
                                          ),
                                        ),
                                      );
                                    },
                                    child: _buildServiceCard(item),
                                  ),
                                );
                              },
                            ),
                    ),

                    const SizedBox(height: 16),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),

      // ── Liquid Floating Bottom Navigation Bar ──
      bottomNavigationBar: LiquidBottomNavBar(
        selectedIndex: _currentNavIndex,
        onTabSelected: (index) {
          setState(() => _currentNavIndex = index);
        },
        items: _buildNavItems(),
      ),
    );
  }



  void _showServiceSelectionModal() {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      backgroundColor: Colors.white,
      builder: (ctx) {
        return Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Center(
                child: Container(
                  width: 40,
                  height: 4,
                  decoration: BoxDecoration(
                    color: Colors.grey.shade300,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              const SizedBox(height: 16),
              const Text(
                'Pilih Jenis Pelayanan',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Color(0xFF0F172A),
                ),
              ),
              const SizedBox(height: 4),
              const Text(
                'Silakan pilih jenis sakramen / misa pelayanan yang Anda butuhkan',
                style: TextStyle(
                  fontSize: 12.5,
                  color: Color(0xFF64748B),
                ),
              ),
              const SizedBox(height: 20),

              // Option 1: Perminyakan Suci
              ListTile(
                contentPadding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(14),
                  side: BorderSide(color: Colors.grey.shade200),
                ),
                leading: Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: const Color(0xFF1E5399).withOpacity(0.1),
                    shape: BoxShape.circle,
                  ),
                  child: const Icon(Icons.sanitizer_rounded,
                      color: Color(0xFF1E5399)),
                ),
                title: const Text(
                  'Sakramen Perminyakan',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
                ),
                subtitle: const Text(
                  'Pelayanan minyak suci untuk orang sakit / lansia',
                  style: TextStyle(fontSize: 12, color: Color(0xFF64748B)),
                ),
                trailing: const Icon(Icons.arrow_forward_ios_rounded, size: 16),
                onTap: () async {
                  Navigator.pop(ctx);
                  await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => CreatePerminyakanScreen(
                        userId: _userId,
                        user: widget.user,
                      ),
                    ),
                  );
                  widget.onRefresh();
                },
              ),

              const SizedBox(height: 12),

              // Option 2: Misa Kedukaan
              ListTile(
                contentPadding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(14),
                  side: BorderSide(color: Colors.grey.shade200),
                ),
                leading: Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: const Color(0xFF0D9488).withOpacity(0.1),
                    shape: BoxShape.circle,
                  ),
                  child: const Icon(Icons.personal_injury_rounded,
                      color: Color(0xFF0D9488)),
                ),
                title: const Text(
                  'Misa Pelayanan Kedukaan',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15),
                ),
                subtitle: const Text(
                  'Misa Tutup Peti, Requiem, Pemakaman, 7 Hari, dll',
                  style: TextStyle(fontSize: 12, color: Color(0xFF64748B)),
                ),
                trailing: const Icon(Icons.arrow_forward_ios_rounded, size: 16),
                onTap: () async {
                  Navigator.pop(ctx);
                  await Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (_) => CreateKedukaanScreen(
                        userId: _userId,
                        user: widget.user,
                      ),
                    ),
                  );
                  widget.onRefresh();
                },
              ),
              const SizedBox(height: 16),
            ],
          ),
        );
      },
    );
  }

  // ── Helpers ──

  String _statusLabel(String status) {
    switch (status.toUpperCase()) {
      case 'ACCEPTED':
        return 'Dikonfirmasi';
      case 'PENDING':
        return 'Menunggu';
      case 'REJECTED':
        return 'Ditolak';
      default:
        return status;
    }
  }

  Color _urgencyColor(String urgency) {
    final u = urgency.toLowerCase();
    if (u.contains('darurat') || u.contains('kritis')) return Colors.red.shade700;
    if (u.contains('penting')) return Colors.amber.shade700;
    return Colors.blue.shade600;
  }

  List<DashboardCardItem> get _displayCardItems {
    final List<DashboardCardItem> cardList = [];

    for (final order in widget.orders.where((o) => o.isActiveDashboardOrder)) {
      if (order.items.isNotEmpty) {
        for (final item in order.items) {
          String scheduleStr = item.scheduledDate;
          if (item.scheduledTimeStart.isNotEmpty) {
            scheduleStr = '${item.scheduledDate} • ${item.scheduledTimeStart}';
            if (item.scheduledTimeEnd.isNotEmpty) {
              scheduleStr += ' - ${item.scheduledTimeEnd} WIB';
            } else {
              scheduleStr += ' WIB';
            }
          }

          cardList.add(
            DashboardCardItem(
              parentOrder: order,
              title: item.itemName,
              dateSchedule: scheduleStr,
              location: item.locationName.isNotEmpty
                  ? item.locationName
                  : order.displayAddress,
              penerimaName: order.penerimaName,
            ),
          );
        }
      } else {
        cardList.add(
          DashboardCardItem(
            parentOrder: order,
            title: order.categoryName,
            dateSchedule: order.fullScheduleLabel,
            location: order.displayAddress,
            penerimaName: order.penerimaName,
          ),
        );
      }
    }

    return cardList;
  }

  // ── Redesigned Service Card ──
  Widget _buildServiceCard(DashboardCardItem item) {
    final order = item.parentOrder;
    final isConfirmed = order.status.toUpperCase() == 'ACCEPTED';
    final urgencyColor = _urgencyColor(order.urgencyName);
    final statusLabel = _statusLabel(order.status);

    Color accentColor;
    if (order.status.toUpperCase() == 'ACCEPTED') {
      accentColor = Colors.teal;
    } else if (order.status.toUpperCase() == 'REJECTED') {
      accentColor = Colors.red.shade700;
    } else {
      accentColor = const Color(0xFF1E5399);
    }

    return Container(
      width: 230,
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(18),
        boxShadow: [
          BoxShadow(
            color: accentColor.withOpacity(0.13),
            blurRadius: 18,
            spreadRadius: 1,
            offset: const Offset(0, 6),
          ),
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(18),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // ── Image Header ──
            SizedBox(
              height: 118,
              child: Stack(
                children: [
                  Positioned.fill(
                    child: Image.asset(
                      'assets/images/church_1.jpg',
                      fit: BoxFit.cover,
                    ),
                  ),
                  Positioned.fill(
                    child: Container(
                      decoration: BoxDecoration(
                        gradient: LinearGradient(
                          colors: [
                            Colors.black.withOpacity(0.0),
                            Colors.black.withOpacity(0.75),
                          ],
                          begin: Alignment.topCenter,
                          end: Alignment.bottomCenter,
                        ),
                      ),
                    ),
                  ),
                  // Status pill (top-left)
                  Positioned(
                    top: 10,
                    left: 10,
                    child: Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 3.5),
                      decoration: BoxDecoration(
                        color: accentColor,
                        borderRadius: BorderRadius.circular(20),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(
                            isConfirmed
                                ? Icons.check_circle_rounded
                                : Icons.hourglass_bottom_rounded,
                            color: Colors.white,
                            size: 10,
                          ),
                          const SizedBox(width: 4),
                          Text(
                            statusLabel,
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 9,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  // Location / Address (bottom of image)
                  Positioned(
                    bottom: 8,
                    left: 10,
                    right: 10,
                    child: Row(
                      children: [
                        const Icon(Icons.location_on_rounded,
                            color: Colors.white, size: 12),
                        const SizedBox(width: 4),
                        Expanded(
                          child: Text(
                            item.location,
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 11,
                              fontWeight: FontWeight.w600,
                              shadows: [
                                Shadow(
                                  blurRadius: 4,
                                  color: Colors.black45,
                                  offset: Offset(0, 1),
                                ),
                              ],
                            ),
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            // ── Urgency accent strip ──
            Container(height: 3, color: urgencyColor),

            // ── Card body ──
            Padding(
              padding: const EdgeInsets.fromLTRB(12, 10, 12, 12),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Category / Item Misa Name badge
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 7, vertical: 2.5),
                    decoration: BoxDecoration(
                      color: const Color(0xFF1E5399).withOpacity(0.08),
                      borderRadius: BorderRadius.circular(6),
                    ),
                    child: Text(
                      item.title,
                      style: const TextStyle(
                        fontSize: 9.5,
                        fontWeight: FontWeight.w700,
                        color: Color(0xFF1E5399),
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                  ),
                  const SizedBox(height: 6),
                  // Nama penerima sakramen — main title
                  Text(
                    item.penerimaName,
                    style: const TextStyle(
                      fontSize: 13.5,
                      fontWeight: FontWeight.bold,
                      color: Color(0xFF0F172A),
                      height: 1.2,
                    ),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                  const SizedBox(height: 5),
                  // Gender + Usia
                  if (order.genderLabel.isNotEmpty || order.usiaLabel.isNotEmpty)
                    Padding(
                      padding: const EdgeInsets.only(bottom: 5),
                      child: Row(
                        children: [
                          if (order.genderLabel.isNotEmpty) ...[
                            const Icon(Icons.person_outline_rounded,
                                size: 12, color: Color(0xFF64748B)),
                            const SizedBox(width: 3),
                            Text(
                              order.genderLabel,
                              style: const TextStyle(
                                  fontSize: 10.5, color: Color(0xFF64748B)),
                            ),
                          ],
                          if (order.genderLabel.isNotEmpty &&
                              order.usiaLabel.isNotEmpty)
                            const SizedBox(width: 8),
                          if (order.usiaLabel.isNotEmpty) ...[
                            const Icon(Icons.cake_outlined,
                                size: 12, color: Color(0xFF64748B)),
                            const SizedBox(width: 3),
                            Text(
                              order.usiaLabel,
                              style: const TextStyle(
                                  fontSize: 10.5, color: Color(0xFF64748B)),
                            ),
                          ],
                        ],
                      ),
                    ),
                  // Date + Start Time + urgency pill
                  Row(
                    children: [
                      const Icon(Icons.calendar_today_outlined,
                          size: 11, color: Color(0xFF94A3B8)),
                      const SizedBox(width: 4),
                      Expanded(
                        child: Text(
                          item.dateSchedule,
                          style: const TextStyle(
                            fontSize: 10,
                            color: Color(0xFF64748B),
                            fontWeight: FontWeight.w600,
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                      const SizedBox(width: 4),
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 6, vertical: 2),
                        decoration: BoxDecoration(
                          color: urgencyColor.withOpacity(0.12),
                          borderRadius: BorderRadius.circular(5),
                        ),
                        child: Text(
                          order.urgencyName,
                          style: TextStyle(
                            fontSize: 9,
                            fontWeight: FontWeight.w700,
                            color: urgencyColor,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class DashboardCardItem {
  final Order parentOrder;
  final String title;
  final String dateSchedule;
  final String location;
  final String penerimaName;

  DashboardCardItem({
    required this.parentOrder,
    required this.title,
    required this.dateSchedule,
    required this.location,
    required this.penerimaName,
  });
}
