// Generated by Codex Agent

import 'package:flutter/material.dart';
import '../../core/models/models.dart';
import '../../core/widgets/liquid_bottom_nav_bar.dart';
import '../orders/create_perminyakan_screen.dart';
import '../chat/chat_screen.dart';

class UmatDashboardView extends StatefulWidget {
  final Map<String, dynamic> user;
  final List<Order> orders;
  final VoidCallback onRefresh;
  final VoidCallback onLogout;

  const UmatDashboardView({
    Key? key,
    required this.user,
    required this.orders,
    required this.onRefresh,
    required this.onLogout,
  }) : super(key: key);

  @override
  State<UmatDashboardView> createState() => _UmatDashboardViewState();
}

class _UmatDashboardViewState extends State<UmatDashboardView> {
  int _currentNavIndex = 0;

  int? get _userId {
    final raw = widget.user['id'] ?? widget.user['userId'] ?? widget.user['user_id'];
    return raw != null ? int.tryParse(raw.toString()) : null;
  }

  @override
  Widget build(BuildContext context) {
    final String userName =
        widget.user['fullName'] ?? widget.user['full_name'] ?? 'Umat';
    final String pengurusPos =
        widget.user['pengurusPosition'] ?? widget.user['pengurus_position'] ?? '';
    final String? startDate =
        widget.user['jabatanStartDate'] ?? widget.user['jabatan_start_date'];
    final String? endDate =
        widget.user['jabatanEndDate'] ?? widget.user['jabatan_end_date'];
    final int? startYear =
        widget.user['jabatanStartYear'] ?? widget.user['jabatan_start_year'];
    final int? endYear =
        widget.user['jabatanEndYear'] ?? widget.user['jabatan_end_year'];
    final bool isJabatanActive =
        widget.user['isJabatanActive'] ?? widget.user['is_jabatan_active'] ?? false;
    final String accountStatus =
        widget.user['accountStatus'] ?? widget.user['account_status'] ?? 'PENDING';
    final bool isApproved = accountStatus == 'APPROVED';

    String positionTitle = 'Umat (Anggota)';
    if (pengurusPos == 'KETUA') positionTitle = 'Umat — Ketua Lingkungan';
    if (pengurusPos == 'WAKIL') positionTitle = 'Umat — Wakil Ketua';
    if (pengurusPos == 'SEKRETARIS') positionTitle = 'Umat — Sekretaris';

    final String periodeText =
        (startDate != null && endDate != null && startDate.isNotEmpty && endDate.isNotEmpty)
            ? '$startDate - $endDate'
            : (startYear != null && endYear != null ? '$startYear - $endYear' : '');

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      body: SafeArea(
        child: Column(
          children: [
            // ── 1. Top Header Bar (same as Romo) ──
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 8, 20, 6),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Hi, $userName',
                          style: const TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF0F172A),
                            letterSpacing: -0.3,
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                        const SizedBox(height: 3),
                        Row(
                          children: [
                            Text(
                              positionTitle,
                              style: const TextStyle(
                                fontSize: 12,
                                fontWeight: FontWeight.bold,
                                color: Color(0xFF1E5399),
                              ),
                            ),
                            const SizedBox(width: 6),
                            Container(
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 5, vertical: 1.5),
                              decoration: BoxDecoration(
                                color: isApproved
                                    ? Colors.green.shade600
                                    : const Color(0xFFD97706),
                                borderRadius: BorderRadius.circular(5),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  Icon(
                                    isApproved
                                        ? Icons.check_circle_rounded
                                        : Icons.hourglass_top_rounded,
                                    size: 9.5,
                                    color: Colors.white,
                                  ),
                                  const SizedBox(width: 3),
                                  Text(
                                    isApproved
                                        ? 'Disetujui'
                                        : 'Menunggu Verifikasi',
                                    style: const TextStyle(
                                      color: Colors.white,
                                      fontSize: 8.5,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                        if (startDate != null &&
                            endDate != null &&
                            startDate.isNotEmpty &&
                            endDate.isNotEmpty) ...[
                          const SizedBox(height: 3),
                          Row(
                            children: [
                              Text(
                                'Mulai: $startDate',
                                style: const TextStyle(
                                    fontSize: 10.5,
                                    fontWeight: FontWeight.w500,
                                    color: Color(0xFF64748B)),
                              ),
                              const SizedBox(width: 10),
                              Text(
                                'Selesai: $endDate',
                                style: const TextStyle(
                                    fontSize: 10.5,
                                    fontWeight: FontWeight.w500,
                                    color: Color(0xFF64748B)),
                              ),
                            ],
                          ),
                        ] else if (periodeText.isNotEmpty) ...[
                          const SizedBox(height: 2),
                          Text(
                            'Masa Bakti: $periodeText',
                            style: const TextStyle(
                                fontSize: 10.5, color: Color(0xFF64748B)),
                          ),
                        ],
                      ],
                    ),
                  ),
                  Row(
                    children: [
                      // Bell icon with badge
                      Stack(
                        clipBehavior: Clip.none,
                        children: [
                          IconButton(
                            icon: const Icon(Icons.notifications_none_rounded,
                                color: Color(0xFF1E5399), size: 26),
                            onPressed: () {},
                          ),
                          Positioned(
                            top: 6,
                            right: 6,
                            child: Container(
                              padding: const EdgeInsets.all(4),
                              decoration: const BoxDecoration(
                                color: Colors.redAccent,
                                shape: BoxShape.circle,
                              ),
                              constraints: const BoxConstraints(
                                  minWidth: 15, minHeight: 15),
                              child: const Text(
                                '1',
                                style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 9.5,
                                    fontWeight: FontWeight.bold),
                                textAlign: TextAlign.center,
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(width: 4),
                      // Mail icon with badge
                      Stack(
                        clipBehavior: Clip.none,
                        children: [
                          IconButton(
                            icon: const Icon(Icons.mail_outline_rounded,
                                color: Color(0xFF1E5399), size: 26),
                            onPressed: () {},
                          ),
                          Positioned(
                            top: 6,
                            right: 6,
                            child: Container(
                              padding: const EdgeInsets.all(4),
                              decoration: const BoxDecoration(
                                color: Colors.redAccent,
                                shape: BoxShape.circle,
                              ),
                              constraints: const BoxConstraints(
                                  minWidth: 15, minHeight: 15),
                              child: const Text(
                                '2',
                                style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 9.5,
                                    fontWeight: FontWeight.bold),
                                textAlign: TextAlign.center,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ),

            // ── 2. Scrollable Body ──
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.only(bottom: 32),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Cross Banner (same as Romo)
                    Padding(
                      padding: const EdgeInsets.fromLTRB(20, 8, 20, 0),
                      child: Container(
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(22),
                          boxShadow: [
                            BoxShadow(
                              color:
                                  const Color(0xFF1E5399).withOpacity(0.18),
                              blurRadius: 24,
                              spreadRadius: 2,
                              offset: const Offset(0, 8),
                            ),
                            BoxShadow(
                              color: Colors.black.withOpacity(0.08),
                              blurRadius: 10,
                              offset: const Offset(0, 4),
                            ),
                          ],
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(22),
                          child: AspectRatio(
                            aspectRatio: 16 / 9,
                            child: Image.asset(
                              'assets/images/cross_banner.jpg',
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ),

                    // ── 3. Spiritual Quote (same as Romo) ──
                    Padding(
                      padding: const EdgeInsets.fromLTRB(28, 16, 28, 20),
                      child: Column(
                        children: const [
                          Text(
                            '" Sungguh, Allah itu keselamatanku; aku percaya dengan tidak gementar, sebab Tuhan Allah itu kekuatanku dan mazmurku, Ia telah menjadi keselamatanku. "',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 13,
                              fontStyle: FontStyle.italic,
                              color: Color(0xFF334155),
                              height: 1.4,
                            ),
                          ),
                          SizedBox(height: 6),
                          Text(
                            '- Yesaya 12:2 -',
                            style: TextStyle(
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                              color: Color(0xFF64748B),
                            ),
                          ),
                        ],
                      ),
                    ),

                    // ── 4. Daftar Permintaan Pelayanan Section ──
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 20),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const SizedBox(
                            width: 180,
                            child: Text(
                              'Daftar\nPermintaan\nPelayanan',
                              style: TextStyle(
                                fontSize: 20,
                                fontWeight: FontWeight.bold,
                                color: Color(0xFF0F172A),
                                height: 1.2,
                              ),
                            ),
                          ),
                          // Umat-only: Buat Permintaan button (instead of Lihat Lainnya)
                          ElevatedButton(
                            onPressed: () async {
                              await Navigator.push(
                                context,
                                MaterialPageRoute(
                                    builder: (_) =>
                                        CreatePerminyakanScreen(userId: _userId)),
                              );
                              widget.onRefresh();
                            },
                            style: ElevatedButton.styleFrom(
                              backgroundColor: const Color(0xFF1E5399),
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(
                                  horizontal: 14, vertical: 10),
                              shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(14)),
                              elevation: 0,
                            ),
                            child: const Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Icon(Icons.add_rounded, size: 16),
                                SizedBox(width: 5),
                                Text(
                                  'Buat Permintaan\nPelayanan',
                                  style: TextStyle(
                                      fontSize: 11,
                                      fontWeight: FontWeight.w600),
                                  textAlign: TextAlign.center,
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),

                    const SizedBox(height: 14),

                    // Horizontal Cards (from real API orders)
                    SizedBox(
                      height: 230,
                      child: widget.orders.isEmpty
                          ? Padding(
                              padding:
                                  const EdgeInsets.symmetric(horizontal: 20),
                              child: Center(
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Icon(Icons.inbox_rounded,
                                        size: 48,
                                        color: Colors.grey.shade300),
                                    const SizedBox(height: 8),
                                    Text(
                                      'Belum ada permintaan pelayanan.\nTap "Buat Permintaan" untuk membuat baru.',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                          color: Colors.grey.shade500,
                                          fontSize: 13),
                                    ),
                                  ],
                                ),
                              ),
                            )
                          : ListView.builder(
                              scrollDirection: Axis.horizontal,
                              padding:
                                  const EdgeInsets.symmetric(horizontal: 20),
                              itemCount: widget.orders.length,
                              itemBuilder: (context, index) {
                                final order = widget.orders[index];
                                return Padding(
                                  padding:
                                      const EdgeInsets.only(right: 14),
                                  child: _buildServiceCard(
                                    statusBadge:
                                        _statusLabel(order.status),
                                    isConfirmed:
                                        order.status.toUpperCase() ==
                                            'ACCEPTED',
                                    location: order.locationName,
                                    dateTime: order.scheduledDate,
                                    category: order.categoryName,
                                    priorityLabel: order.urgencyName,
                                    priorityColor:
                                        _urgencyColor(order.urgencyName),
                                    priorityIcon:
                                        _urgencyIcon(order.urgencyName),
                                    onTapChat: () {
                                      Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                          builder: (_) => ChatScreen(
                                            groupId: order.id,
                                            orderNumber:
                                                order.orderNumber,
                                            userName: userName,
                                          ),
                                        ),
                                      );
                                    },
                                  ),
                                );
                              },
                            ),
                    ),

                    const SizedBox(height: 16),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),

      // ── Liquid Floating Bottom Navigation Bar ──
      bottomNavigationBar: LiquidBottomNavBar(
        selectedIndex: _currentNavIndex,
        onTabSelected: (index) {
          setState(() => _currentNavIndex = index);
          if (index == 3) {
            _showMenuBottomSheet();
          }
        },
        items: const [
          LiquidNavItem(
            icon: Icons.home_outlined,
            activeIcon: Icons.home_rounded,
            label: 'Beranda',
          ),
          LiquidNavItem(
            icon: Icons.history_outlined,
            activeIcon: Icons.history_rounded,
            label: 'Histori',
          ),
          LiquidNavItem(
            icon: Icons.calendar_today_outlined,
            activeIcon: Icons.calendar_today_rounded,
            label: 'Jadwal',
          ),
          LiquidNavItem(
            icon: Icons.menu_outlined,
            activeIcon: Icons.menu_rounded,
            label: 'Menu',
          ),
        ],
      ),
    );
  }

  void _showMenuBottomSheet() {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (ctx) {
        final userName =
            widget.user['fullName'] ?? widget.user['full_name'] ?? 'Umat';
        final phone =
            widget.user['phoneNumber'] ?? widget.user['phone_number'] ?? '';
        return Padding(
          padding: const EdgeInsets.all(24.0),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                    color: Colors.grey.shade300,
                    borderRadius: BorderRadius.circular(2)),
              ),
              const SizedBox(height: 16),
              ListTile(
                leading: const CircleAvatar(
                    backgroundColor: Color(0xFF1E5399),
                    child: Icon(Icons.person, color: Colors.white)),
                title: Text(userName,
                    style:
                        const TextStyle(fontWeight: FontWeight.bold)),
                subtitle: Text(phone),
              ),
              const Divider(height: 24),
              ListTile(
                leading: const Icon(Icons.add_circle_outline_rounded,
                    color: Color(0xFF1E5399)),
                title: const Text('Buat Permintaan Pelayanan'),
                onTap: () async {
                  Navigator.pop(ctx);
                  await Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (_) => CreatePerminyakanScreen(userId: _userId)),
                  );
                  widget.onRefresh();
                },
              ),
              ListTile(
                leading: const Icon(Icons.refresh_rounded,
                    color: Color(0xFF1E5399)),
                title: const Text('Refresh Data Pelayanan'),
                onTap: () {
                  Navigator.pop(ctx);
                  widget.onRefresh();
                },
              ),
              ListTile(
                leading:
                    const Icon(Icons.logout_rounded, color: Colors.redAccent),
                title: const Text('Keluar (Logout)',
                    style: TextStyle(
                        color: Colors.redAccent,
                        fontWeight: FontWeight.bold)),
                onTap: () {
                  Navigator.pop(ctx);
                  widget.onLogout();
                },
              ),
            ],
          ),
        );
      },
    );
  }

  // ── Helpers ──

  String _statusLabel(String status) {
    switch (status.toUpperCase()) {
      case 'ACCEPTED':
        return 'Kehadiran Dikonfirmasi';
      case 'PENDING':
        return 'Menunggu Konfirmasi Kehadiran';
      case 'UBAH_WAKTU':
        return 'Ubah Waktu Diajukan';
      case 'REJECTED':
        return 'Ditolak';
      default:
        return status;
    }
  }

  Color _urgencyColor(String urgency) {
    final u = urgency.toLowerCase();
    if (u.contains('sangat') || u.contains('segera')) return Colors.red.shade700;
    if (u.contains('penting')) return Colors.amber.shade800;
    return Colors.blue.shade700;
  }

  IconData _urgencyIcon(String urgency) {
    final u = urgency.toLowerCase();
    if (u.contains('sangat') || u.contains('segera')) {
      return Icons.error_outline_rounded;
    }
    if (u.contains('penting')) return Icons.error_outline_rounded;
    return Icons.info_outline_rounded;
  }

  Widget _buildServiceCard({
    required String statusBadge,
    required bool isConfirmed,
    required String location,
    required String dateTime,
    required String category,
    required String priorityLabel,
    required Color priorityColor,
    required IconData priorityIcon,
    required VoidCallback onTapChat,
  }) {
    return GestureDetector(
      onTap: onTapChat,
      child: Container(
        width: 230,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          boxShadow: [
            BoxShadow(
              color: Colors.black.withOpacity(0.07),
              blurRadius: 12,
              offset: const Offset(0, 4),
            ),
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Image Stack with Gradient & Badges
              SizedBox(
                height: 135,
                child: Stack(
                  children: [
                    // Church Background Image
                    Positioned.fill(
                      child: Image.asset(
                        'assets/images/church_1.jpg',
                        fit: BoxFit.cover,
                      ),
                    ),
                    // Dark Gradient Overlay
                    Positioned.fill(
                      child: Container(
                        decoration: BoxDecoration(
                          gradient: LinearGradient(
                            colors: [
                              Colors.black.withOpacity(0.0),
                              Colors.black.withOpacity(0.75),
                            ],
                            begin: Alignment.topCenter,
                            end: Alignment.bottomCenter,
                          ),
                        ),
                      ),
                    ),
                    // Top Left Status Badge
                    Positioned(
                      top: 10,
                      left: 10,
                      right: 44,
                      child: Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 8, vertical: 4),
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(10),
                        ),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Expanded(
                              child: Text(
                                statusBadge,
                                style: const TextStyle(
                                  fontSize: 9.5,
                                  fontWeight: FontWeight.w700,
                                  color: Color(0xFF1E293B),
                                ),
                                overflow: TextOverflow.ellipsis,
                              ),
                            ),
                            const SizedBox(width: 4),
                            Icon(
                              isConfirmed
                                  ? Icons.check_box_rounded
                                  : Icons.hourglass_bottom_rounded,
                              size: 14,
                              color: isConfirmed
                                  ? Colors.teal
                                  : Colors.amber.shade800,
                            ),
                          ],
                        ),
                      ),
                    ),
                    // Top Right User Avatar Badge
                    Positioned(
                      top: 10,
                      right: 10,
                      child: Container(
                        width: 26,
                        height: 26,
                        decoration: BoxDecoration(
                          color: Colors.white,
                          shape: BoxShape.circle,
                          boxShadow: [
                            BoxShadow(
                              color: Colors.black.withOpacity(0.15),
                              blurRadius: 4,
                            ),
                          ],
                        ),
                        child: Icon(
                          isConfirmed
                              ? Icons.person_rounded
                              : Icons.person_outline_rounded,
                          size: 16,
                          color: isConfirmed
                              ? Colors.teal
                              : Colors.amber.shade800,
                        ),
                      ),
                    ),
                    // Bottom Text Overlay
                    Positioned(
                      bottom: 8,
                      left: 10,
                      right: 10,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              const Icon(Icons.location_on_outlined,
                                  color: Colors.white, size: 12),
                              const SizedBox(width: 4),
                              Expanded(
                                child: Text(
                                  location,
                                  style: const TextStyle(
                                    color: Colors.white,
                                    fontSize: 11,
                                    fontWeight: FontWeight.bold,
                                  ),
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 2),
                          Row(
                            children: [
                              const Icon(Icons.calendar_today_outlined,
                                  color: Colors.white70, size: 11),
                              const SizedBox(width: 4),
                              Expanded(
                                child: Text(
                                  dateTime,
                                  style: const TextStyle(
                                    color: Colors.white70,
                                    fontSize: 10,
                                    fontWeight: FontWeight.w500,
                                  ),
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),

              // Bottom White Area: Category & Priority
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      category,
                      style: const TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: Color(0xFF1E293B),
                      ),
                    ),
                    const SizedBox(height: 4),
                    Row(
                      children: [
                        Icon(priorityIcon, size: 14, color: priorityColor),
                        const SizedBox(width: 4),
                        Expanded(
                          child: Text(
                            priorityLabel,
                            style: TextStyle(
                              fontSize: 11,
                              fontWeight: FontWeight.w600,
                              color: priorityColor,
                            ),
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
