// Generated by Codex Agent

import 'package:flutter/material.dart';
import '../../core/constants/app_constants.dart';
import '../../core/models/models.dart';
import '../../core/widgets/liquid_bottom_nav_bar.dart';
import '../orders/create_order_screen.dart';
import '../chat/chat_screen.dart';

class UmatDashboardView extends StatefulWidget {
  final Map<String, dynamic> user;
  final List<Order> orders;
  final VoidCallback onRefresh;
  final VoidCallback onLogout;

  const UmatDashboardView({
    Key? key,
    required this.user,
    required this.orders,
    required this.onRefresh,
    required this.onLogout,
  }) : super(key: key);

  @override
  State<UmatDashboardView> createState() => _UmatDashboardViewState();
}

class _UmatDashboardViewState extends State<UmatDashboardView>
    with SingleTickerProviderStateMixin {
  int _currentNavIndex = 0;
  late AnimationController _fadeCtrl;
  late Animation<double> _fadeAnim;

  // Daily verses rotation
  final List<Map<String, String>> _verses = [
    {
      'text':
          'Sungguh, Allah itu keselamatanku; aku percaya dengan tidak gemetar, sebab Tuhan Allah itu kekuatanku dan mazmurku; Ia telah menjadi keselamatanku.',
      'ref': 'Yesaya 12:2',
    },
    {
      'text':
          'Sebab Aku ini mengetahui rancangan-rancangan apa yang ada pada-Ku mengenai kamu, demikianlah firman Tuhan, yaitu rancangan damai sejahtera dan bukan rancangan kecelakaan, untuk memberikan kepadamu hari depan yang penuh harapan.',
      'ref': 'Yeremia 29:11',
    },
    {
      'text':
          'Karena itu janganlah kamu kuatir akan hari besok, karena hari besok mempunyai kesusahannya sendiri. Kesusahan sehari cukuplah untuk sehari.',
      'ref': 'Matius 6:34',
    },
    {
      'text':
          'Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku.',
      'ref': 'Filipi 4:13',
    },
  ];

  late Map<String, String> _todayVerse;

  @override
  void initState() {
    super.initState();
    _fadeCtrl =
        AnimationController(vsync: this, duration: const Duration(milliseconds: 600));
    _fadeAnim = CurvedAnimation(parent: _fadeCtrl, curve: Curves.easeOut);
    _fadeCtrl.forward();

    final dayIndex = DateTime.now().weekday % _verses.length;
    _todayVerse = _verses[dayIndex];
  }

  @override
  void dispose() {
    _fadeCtrl.dispose();
    super.dispose();
  }

  Color _statusColor(String status) {
    switch (status.toUpperCase()) {
      case 'ACCEPTED':
      case 'KEHADIRAN_DIKONFIRMASI':
        return Colors.green.shade600;
      case 'PENDING':
      case 'MENUNGGU_KONFIRMASI':
        return Colors.amber.shade700;
      case 'UBAH_WAKTU':
        return Colors.blue.shade600;
      case 'REJECTED':
        return Colors.red.shade600;
      default:
        return Colors.grey.shade600;
    }
  }

  String _statusLabel(String status) {
    switch (status.toUpperCase()) {
      case 'ACCEPTED':
        return 'Kehadiran Dikonfirmasi';
      case 'PENDING':
        return 'Menunggu Konfirmasi Kehadiran';
      case 'UBAH_WAKTU':
        return 'Ubah Waktu Diajukan';
      case 'REJECTED':
        return 'Ditolak';
      default:
        return status;
    }
  }

  IconData _statusIcon(String status) {
    switch (status.toUpperCase()) {
      case 'ACCEPTED':
        return Icons.check_circle_rounded;
      case 'PENDING':
        return Icons.hourglass_top_rounded;
      case 'UBAH_WAKTU':
        return Icons.schedule_rounded;
      case 'REJECTED':
        return Icons.cancel_rounded;
      default:
        return Icons.info_rounded;
    }
  }

  Color _urgencyColor(String urgency) {
    final u = urgency.toLowerCase();
    if (u.contains('sangat') || u.contains('butuh segera')) {
      return Colors.red.shade600;
    } else if (u.contains('penting')) {
      return Colors.amber.shade700;
    }
    return Colors.blue.shade600;
  }

  IconData _urgencyIcon(String urgency) {
    final u = urgency.toLowerCase();
    if (u.contains('sangat') || u.contains('butuh segera')) {
      return Icons.priority_high_rounded;
    } else if (u.contains('penting')) {
      return Icons.warning_amber_rounded;
    }
    return Icons.info_outline_rounded;
  }

  Widget _buildBeranda(BuildContext context) {
    final String userName =
        widget.user['fullName'] ?? widget.user['full_name'] ?? 'Umat';
    final String parokiName =
        widget.user['parokiName'] ?? widget.user['paroki_name'] ?? 'Paroki';
    final String lingkunganName =
        widget.user['lingkunganName'] ?? widget.user['lingkungan_name'] ?? '';
    final String accountStatus =
        widget.user['accountStatus'] ?? widget.user['account_status'] ?? 'PENDING';
    final bool isApproved = accountStatus == 'APPROVED';

    return FadeTransition(
      opacity: _fadeAnim,
      child: CustomScrollView(
        physics: const BouncingScrollPhysics(),
        slivers: [
          // ── Hero Header ──
          SliverToBoxAdapter(
            child: Stack(
              children: [
                // Church photo background
                Container(
                  height: 220,
                  width: double.infinity,
                  decoration: const BoxDecoration(
                    color: Color(0xFF1E3A8A),
                  ),
                  child: Image.network(
                    'https://images.unsplash.com/photo-1584652868574-0669a574b63c?w=800&q=80',
                    fit: BoxFit.cover,
                    color: Colors.black.withOpacity(0.35),
                    colorBlendMode: BlendMode.darken,
                    errorBuilder: (_, __, ___) => Container(
                      color: AppConstants.primaryBlue,
                      child: const Icon(Icons.church_rounded,
                          size: 80, color: Colors.white30),
                    ),
                  ),
                ),
                // Gradient fade-to-white at bottom
                Positioned(
                  bottom: 0,
                  left: 0,
                  right: 0,
                  child: Container(
                    height: 80,
                    decoration: BoxDecoration(
                      gradient: LinearGradient(
                        begin: Alignment.topCenter,
                        end: Alignment.bottomCenter,
                        colors: [
                          Colors.transparent,
                          AppConstants.bgCanvas.withOpacity(0.95),
                        ],
                      ),
                    ),
                  ),
                ),
                // Top bar: Hi [name] + notification + message
                SafeArea(
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(20, 12, 16, 0),
                    child: Row(
                      children: [
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Hi, ${userName.split(' ').first}',
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 22,
                                  fontWeight: FontWeight.bold,
                                  shadows: [
                                    Shadow(
                                        color: Colors.black45,
                                        blurRadius: 6,
                                        offset: Offset(0, 2))
                                  ],
                                ),
                              ),
                              const SizedBox(height: 2),
                              Row(
                                children: [
                                  Icon(
                                    isApproved
                                        ? Icons.verified_rounded
                                        : Icons.hourglass_top_rounded,
                                    size: 13,
                                    color: isApproved
                                        ? Colors.greenAccent
                                        : Colors.amberAccent,
                                  ),
                                  const SizedBox(width: 4),
                                  Text(
                                    isApproved
                                        ? 'Umat Terverifikasi'
                                        : 'Menunggu Verifikasi',
                                    style: TextStyle(
                                      color: isApproved
                                          ? Colors.greenAccent
                                          : Colors.amberAccent,
                                      fontSize: 12,
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ),
                        // Notification bell
                        Container(
                          margin: const EdgeInsets.only(right: 8),
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0.15),
                            borderRadius: BorderRadius.circular(10),
                          ),
                          child: Stack(
                            children: [
                              IconButton(
                                icon: const Icon(Icons.notifications_rounded,
                                    color: Colors.white, size: 24),
                                onPressed: () {},
                              ),
                              Positioned(
                                top: 8,
                                right: 8,
                                child: Container(
                                  width: 9,
                                  height: 9,
                                  decoration: const BoxDecoration(
                                    color: Colors.redAccent,
                                    shape: BoxShape.circle,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        // Message icon
                        Container(
                          decoration: BoxDecoration(
                            color: Colors.white.withOpacity(0.15),
                            borderRadius: BorderRadius.circular(10),
                          ),
                          child: IconButton(
                            icon: const Icon(Icons.mail_outline_rounded,
                                color: Colors.white, size: 24),
                            onPressed: () {},
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),

          // ── Daily Verse ──
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(20, 8, 20, 16),
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.06),
                      blurRadius: 12,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Column(
                  children: [
                    Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.all(6),
                          decoration: BoxDecoration(
                            color: AppConstants.primaryBlue.withOpacity(0.08),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: const Icon(Icons.menu_book_rounded,
                              color: AppConstants.primaryBlue, size: 18),
                        ),
                        const SizedBox(width: 10),
                        const Text(
                          'Ayat Renungan Hari Ini',
                          style: TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.bold,
                            color: AppConstants.primaryBlue,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Text(
                      '" ${_todayVerse['text']} "',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 13.5,
                        color: AppConstants.textDark.withOpacity(0.85),
                        fontStyle: FontStyle.italic,
                        height: 1.6,
                      ),
                    ),
                    const SizedBox(height: 10),
                    Text(
                      '— ${_todayVerse['ref']} —',
                      style: TextStyle(
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                        color: AppConstants.textMuted.withOpacity(0.8),
                        letterSpacing: 0.3,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),

          // ── Location badge ──
          if (parokiName.isNotEmpty)
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(20, 0, 20, 16),
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                  decoration: BoxDecoration(
                    color: AppConstants.primaryBlue.withOpacity(0.06),
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(
                        color: AppConstants.primaryBlue.withOpacity(0.15)),
                  ),
                  child: Row(
                    children: [
                      const Icon(Icons.church_outlined,
                          color: AppConstants.primaryBlue, size: 18),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          lingkunganName.isNotEmpty
                              ? '$parokiName · $lingkunganName'
                              : parokiName,
                          style: const TextStyle(
                            fontSize: 13,
                            color: AppConstants.primaryBlue,
                            fontWeight: FontWeight.w600,
                          ),
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),

          // ── Daftar Permintaan Pelayanan Header ──
          SliverToBoxAdapter(
            child: Padding(
              padding: const EdgeInsets.fromLTRB(20, 0, 20, 12),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.end,
                children: [
                  const Expanded(
                    child: Text(
                      'Daftar Permintaan\nPelayanan',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: AppConstants.textDark,
                        height: 1.3,
                      ),
                    ),
                  ),
                  ElevatedButton.icon(
                    onPressed: () async {
                      await Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (_) => const CreateOrderScreen()),
                      );
                      widget.onRefresh();
                    },
                    icon: const Icon(Icons.add_circle_outline_rounded,
                        size: 16, color: Colors.white),
                    label: const Text(
                      'Buat Permintaan',
                      style: TextStyle(
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                          color: Colors.white),
                    ),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppConstants.primaryBlue,
                      padding:
                          const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(12)),
                      elevation: 2,
                    ),
                  ),
                ],
              ),
            ),
          ),

          // ── Horizontal Cards ──
          if (widget.orders.isEmpty)
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.all(40),
                child: Column(
                  children: [
                    Icon(Icons.inbox_rounded,
                        size: 64, color: Colors.grey.shade300),
                    const SizedBox(height: 12),
                    Text(
                      'Belum ada permintaan pelayanan',
                      style: TextStyle(
                          color: Colors.grey.shade500, fontSize: 14),
                    ),
                    const SizedBox(height: 6),
                    Text(
                      'Tap "Buat Permintaan" untuk membuat baru',
                      style: TextStyle(
                          color: Colors.grey.shade400, fontSize: 12),
                    ),
                  ],
                ),
              ),
            )
          else
            SliverToBoxAdapter(
              child: SizedBox(
                height: 210,
                child: ListView.builder(
                  scrollDirection: Axis.horizontal,
                  physics: const BouncingScrollPhysics(),
                  padding: const EdgeInsets.fromLTRB(20, 0, 20, 4),
                  itemCount: widget.orders.length,
                  itemBuilder: (context, index) {
                    final order = widget.orders[index];
                    final statusColor = _statusColor(order.status);
                    final statusLabel = _statusLabel(order.status);
                    final statusIcon = _statusIcon(order.status);

                    return GestureDetector(
                      onTap: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                            builder: (_) => ChatScreen(
                              groupId: order.id,
                              orderNumber: order.orderNumber,
                              userName: widget.user['fullName'] ??
                                  widget.user['full_name'] ??
                                  'Umat',
                            ),
                          ),
                        );
                      },
                      child: Container(
                        width: 200,
                        margin: const EdgeInsets.only(right: 14),
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(16),
                          boxShadow: [
                            BoxShadow(
                              color: Colors.black.withOpacity(0.10),
                              blurRadius: 10,
                              offset: const Offset(0, 4),
                            ),
                          ],
                        ),
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(16),
                          child: Stack(
                            children: [
                              // Background image (church/location)
                              Positioned.fill(
                                child: Image.network(
                                  'https://images.unsplash.com/photo-1494548162494-384bba4ab999?w=400&q=70',
                                  fit: BoxFit.cover,
                                  errorBuilder: (_, __, ___) => Container(
                                    color: AppConstants.primaryBlue
                                        .withOpacity(0.15),
                                    child: const Icon(Icons.church_rounded,
                                        size: 60, color: Colors.white24),
                                  ),
                                ),
                              ),
                              // Dark overlay
                              Positioned.fill(
                                child: Container(
                                  decoration: BoxDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment.topCenter,
                                      end: Alignment.bottomCenter,
                                      colors: [
                                        Colors.black.withOpacity(0.25),
                                        Colors.black.withOpacity(0.72),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                              // Content
                              Positioned.fill(
                                child: Padding(
                                  padding: const EdgeInsets.all(12),
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      // Status badge top
                                      Container(
                                        padding: const EdgeInsets.symmetric(
                                            horizontal: 8, vertical: 4),
                                        decoration: BoxDecoration(
                                          color: statusColor.withOpacity(0.92),
                                          borderRadius:
                                              BorderRadius.circular(20),
                                        ),
                                        child: Row(
                                          mainAxisSize: MainAxisSize.min,
                                          children: [
                                            Icon(statusIcon,
                                                size: 11, color: Colors.white),
                                            const SizedBox(width: 4),
                                            Flexible(
                                              child: Text(
                                                statusLabel,
                                                style: const TextStyle(
                                                  color: Colors.white,
                                                  fontSize: 9.5,
                                                  fontWeight: FontWeight.bold,
                                                ),
                                                overflow: TextOverflow.ellipsis,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                      const Spacer(),
                                      // Location
                                      Row(
                                        children: [
                                          const Icon(Icons.location_on_rounded,
                                              size: 12, color: Colors.white70),
                                          const SizedBox(width: 4),
                                          Expanded(
                                            child: Text(
                                              order.locationName,
                                              style: const TextStyle(
                                                  color: Colors.white70,
                                                  fontSize: 11),
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 4),
                                      // Date
                                      Row(
                                        children: [
                                          const Icon(Icons.calendar_today_rounded,
                                              size: 12, color: Colors.white70),
                                          const SizedBox(width: 4),
                                          Expanded(
                                            child: Text(
                                              order.scheduledDate,
                                              style: const TextStyle(
                                                  color: Colors.white70,
                                                  fontSize: 11),
                                              overflow: TextOverflow.ellipsis,
                                            ),
                                          ),
                                        ],
                                      ),
                                      const SizedBox(height: 6),
                                      // Category name
                                      Text(
                                        order.categoryName,
                                        style: const TextStyle(
                                          color: Colors.white,
                                          fontSize: 13,
                                          fontWeight: FontWeight.bold,
                                        ),
                                        maxLines: 1,
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                      const SizedBox(height: 4),
                                      // Urgency chip
                                      Row(
                                        children: [
                                          Icon(
                                            _urgencyIcon(order.urgencyName),
                                            size: 12,
                                            color: _urgencyColor(order.urgencyName),
                                          ),
                                          const SizedBox(width: 4),
                                          Text(
                                            order.urgencyName,
                                            style: TextStyle(
                                              color: _urgencyColor(order.urgencyName),
                                              fontSize: 11,
                                              fontWeight: FontWeight.w600,
                                            ),
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              // Right-side person icon (pemohon indicator)
                              Positioned(
                                top: 10,
                                right: 10,
                                child: Container(
                                  padding: const EdgeInsets.all(4),
                                  decoration: BoxDecoration(
                                    color: Colors.white.withOpacity(0.2),
                                    borderRadius: BorderRadius.circular(8),
                                  ),
                                  child: const Icon(Icons.person_rounded,
                                      size: 18, color: Colors.white),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    );
                  },
                ),
              ),
            ),

          const SliverToBoxAdapter(child: SizedBox(height: 24)),

          // ── All Orders List Section ──
          if (widget.orders.isNotEmpty) ...[
            const SliverToBoxAdapter(
              child: Padding(
                padding: EdgeInsets.fromLTRB(20, 8, 20, 12),
                child: Text(
                  'Semua Permintaan',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: AppConstants.textDark,
                  ),
                ),
              ),
            ),
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (context, index) {
                  final order = widget.orders[index];
                  final statusColor = _statusColor(order.status);
                  final statusLabel = _statusLabel(order.status);

                  return Container(
                    margin:
                        const EdgeInsets.fromLTRB(20, 0, 20, 12),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(14),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.05),
                          blurRadius: 8,
                          offset: const Offset(0, 2),
                        ),
                      ],
                    ),
                    child: Padding(
                      padding: const EdgeInsets.all(14),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              Expanded(
                                child: Text(
                                  order.orderNumber,
                                  style: const TextStyle(
                                    fontWeight: FontWeight.bold,
                                    color: AppConstants.primaryBlue,
                                    fontSize: 13,
                                  ),
                                ),
                              ),
                              Container(
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 10, vertical: 4),
                                decoration: BoxDecoration(
                                  color: statusColor.withOpacity(0.12),
                                  borderRadius: BorderRadius.circular(20),
                                ),
                                child: Text(
                                  statusLabel,
                                  style: TextStyle(
                                    fontSize: 10.5,
                                    fontWeight: FontWeight.bold,
                                    color: statusColor,
                                  ),
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Text(
                            order.categoryName,
                            style: const TextStyle(
                              fontSize: 15,
                              fontWeight: FontWeight.bold,
                              color: AppConstants.textDark,
                            ),
                          ),
                          const SizedBox(height: 4),
                          Row(
                            children: [
                              const Icon(Icons.location_on_outlined,
                                  size: 14, color: AppConstants.textMuted),
                              const SizedBox(width: 4),
                              Expanded(
                                child: Text(
                                  order.locationName,
                                  style: const TextStyle(
                                      fontSize: 12,
                                      color: AppConstants.textMuted),
                                  overflow: TextOverflow.ellipsis,
                                ),
                              ),
                              const SizedBox(width: 8),
                              const Icon(Icons.calendar_today_outlined,
                                  size: 14, color: AppConstants.textMuted),
                              const SizedBox(width: 4),
                              Text(
                                order.scheduledDate,
                                style: const TextStyle(
                                    fontSize: 12,
                                    color: AppConstants.textMuted),
                              ),
                            ],
                          ),
                          const Divider(height: 16),
                          Row(
                            children: [
                              Row(
                                children: [
                                  Icon(
                                    _urgencyIcon(order.urgencyName),
                                    size: 14,
                                    color: _urgencyColor(order.urgencyName),
                                  ),
                                  const SizedBox(width: 4),
                                  Text(
                                    order.urgencyName,
                                    style: TextStyle(
                                      fontSize: 12,
                                      fontWeight: FontWeight.w600,
                                      color: _urgencyColor(order.urgencyName),
                                    ),
                                  ),
                                ],
                              ),
                              const Spacer(),
                              GestureDetector(
                                onTap: () {
                                  Navigator.push(
                                    context,
                                    MaterialPageRoute(
                                      builder: (_) => ChatScreen(
                                        groupId: order.id,
                                        orderNumber: order.orderNumber,
                                        userName: widget.user['fullName'] ??
                                            widget.user['full_name'] ??
                                            'Umat',
                                      ),
                                    ),
                                  );
                                },
                                child: Container(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 12, vertical: 6),
                                  decoration: BoxDecoration(
                                    color: AppConstants.primaryBlue
                                        .withOpacity(0.08),
                                    borderRadius: BorderRadius.circular(20),
                                  ),
                                  child: const Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      Icon(Icons.chat_bubble_outline_rounded,
                                          size: 14,
                                          color: AppConstants.primaryBlue),
                                      SizedBox(width: 4),
                                      Text(
                                        'Buka Chat',
                                        style: TextStyle(
                                          fontSize: 12,
                                          fontWeight: FontWeight.bold,
                                          color: AppConstants.primaryBlue,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  );
                },
                childCount: widget.orders.length,
              ),
            ),
          ],

          const SliverToBoxAdapter(child: SizedBox(height: 100)),
        ],
      ),
    );
  }

  Widget _buildHistori() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.history_rounded, size: 64, color: Colors.grey.shade300),
          const SizedBox(height: 12),
          Text('Histori Pelayanan',
              style: TextStyle(color: Colors.grey.shade500, fontSize: 16)),
          const SizedBox(height: 6),
          Text('Belum ada histori',
              style: TextStyle(color: Colors.grey.shade400, fontSize: 13)),
        ],
      ),
    );
  }

  Widget _buildJadwal(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.calendar_month_rounded,
              size: 64, color: Colors.grey.shade300),
          const SizedBox(height: 12),
          Text('Jadwal Pelayanan',
              style: TextStyle(color: Colors.grey.shade500, fontSize: 16)),
          const SizedBox(height: 16),
          ElevatedButton.icon(
            onPressed: () async {
              await Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (_) => const CreateOrderScreen()),
              );
              widget.onRefresh();
            },
            icon: const Icon(Icons.add_circle_outline_rounded,
                color: Colors.white, size: 18),
            label: const Text('Buat Permintaan Pelayanan',
                style: TextStyle(color: Colors.white)),
            style: ElevatedButton.styleFrom(
              backgroundColor: AppConstants.primaryBlue,
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12)),
              padding:
                  const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final String userName =
        widget.user['fullName'] ?? widget.user['full_name'] ?? 'Umat';

    Widget body;
    switch (_currentNavIndex) {
      case 1:
        body = _buildHistori();
        break;
      case 2:
        body = _buildJadwal(context);
        break;
      default:
        body = _buildBeranda(context);
    }

    return Scaffold(
      backgroundColor: AppConstants.bgCanvas,
      body: body,
      bottomNavigationBar: LiquidBottomNavBar(
        selectedIndex: _currentNavIndex,
        onTabSelected: (index) {
          if (index == 3) {
            _showMenuBottomSheet(context, userName);
            return;
          }
          setState(() => _currentNavIndex = index);
        },
        items: const [
          LiquidNavItem(
              icon: Icons.home_outlined,
              activeIcon: Icons.home_rounded,
              label: 'Beranda'),
          LiquidNavItem(
              icon: Icons.history_outlined,
              activeIcon: Icons.history_rounded,
              label: 'Histori'),
          LiquidNavItem(
              icon: Icons.calendar_month_outlined,
              activeIcon: Icons.calendar_month_rounded,
              label: 'Jadwal Pelayanan'),
          LiquidNavItem(
              icon: Icons.menu_outlined,
              activeIcon: Icons.menu_rounded,
              label: 'Menu'),
        ],
      ),
    );
  }

  void _showMenuBottomSheet(BuildContext context, String userName) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      builder: (ctx) => Container(
        decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
        ),
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                  color: Colors.grey.shade300,
                  borderRadius: BorderRadius.circular(2)),
            ),
            const SizedBox(height: 20),
            Row(
              children: [
                CircleAvatar(
                  radius: 24,
                  backgroundColor: AppConstants.primaryBlue,
                  child: Text(
                    userName.isNotEmpty ? userName[0].toUpperCase() : 'U',
                    style: const TextStyle(
                        color: Colors.white,
                        fontSize: 20,
                        fontWeight: FontWeight.bold),
                  ),
                ),
                const SizedBox(width: 14),
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(userName,
                        style: const TextStyle(
                            fontWeight: FontWeight.bold, fontSize: 16)),
                    const Text('Umat',
                        style: TextStyle(
                            color: AppConstants.textMuted, fontSize: 13)),
                  ],
                ),
              ],
            ),
            const SizedBox(height: 20),
            const Divider(),
            _menuItem(
              icon: Icons.add_circle_outline_rounded,
              color: AppConstants.primaryBlue,
              label: 'Buat Permintaan Pelayanan',
              onTap: () async {
                Navigator.pop(ctx);
                await Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (_) => const CreateOrderScreen()),
                );
                widget.onRefresh();
              },
            ),
            _menuItem(
              icon: Icons.refresh_rounded,
              color: AppConstants.primaryBlue,
              label: 'Refresh Data',
              onTap: () {
                Navigator.pop(ctx);
                widget.onRefresh();
              },
            ),
            _menuItem(
              icon: Icons.logout_rounded,
              color: Colors.redAccent,
              label: 'Keluar (Logout)',
              textColor: Colors.redAccent,
              onTap: () {
                Navigator.pop(ctx);
                widget.onLogout();
              },
            ),
          ],
        ),
      ),
    );
  }

  Widget _menuItem({
    required IconData icon,
    required Color color,
    required String label,
    Color? textColor,
    required VoidCallback onTap,
  }) {
    return ListTile(
      leading: Container(
        padding: const EdgeInsets.all(8),
        decoration: BoxDecoration(
          color: color.withOpacity(0.1),
          borderRadius: BorderRadius.circular(10),
        ),
        child: Icon(icon, color: color, size: 20),
      ),
      title: Text(
        label,
        style: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w600,
          color: textColor ?? AppConstants.textDark,
        ),
      ),
      trailing:
          const Icon(Icons.chevron_right_rounded, color: AppConstants.textMuted),
      onTap: onTap,
    );
  }
}
