// Generated by Codex Agent
import 'package:flutter/material.dart';
import '../core/constants/app_constants.dart';

class SearchableSelectItem<T> {
  final T value;
  final String label;
  final String? subtitle;

  SearchableSelectItem({
    required this.value,
    required this.label,
    this.subtitle,
  });
}

class SearchableSelectField<T> extends StatelessWidget {
  final String label;
  final String? hint;
  final IconData icon;
  final T? value;
  final List<SearchableSelectItem<T>> items;
  final ValueChanged<T?> onChanged;
  final bool isLoading;
  final String emptyMessage;

  const SearchableSelectField({
    Key? key,
    required this.label,
    this.hint,
    required this.icon,
    required this.value,
    required this.items,
    required this.onChanged,
    this.isLoading = false,
    this.emptyMessage = 'Tidak ada data ditemukan',
  }) : super(key: key);

  String get _selectedLabel {
    if (value == null) return hint ?? 'Pilih $label';
    final found = items.firstWhere(
      (item) => item.value == value,
      orElse: () => SearchableSelectItem(value: value as T, label: ''),
    );
    return found.label.isNotEmpty ? found.label : (hint ?? 'Pilih $label');
  }

  void _showSearchSheet(BuildContext context) {
    if (items.isEmpty && !isLoading) return;

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => _SearchModalSheet<T>(
        title: label,
        icon: icon,
        items: items,
        selectedValue: value,
        emptyMessage: emptyMessage,
        onSelected: (val) {
          Navigator.pop(ctx);
          onChanged(val);
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final hasValue = value != null;

    return Padding(
      padding: const EdgeInsets.only(bottom: 12.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          GestureDetector(
            onTap: isLoading ? null : () => _showSearchSheet(context),
            child: InputDecorator(
              decoration: InputDecoration(
                labelText: label,
                labelStyle: TextStyle(color: Colors.grey.shade600, fontSize: 14),
                filled: true,
                fillColor: const Color(0xFFF7F9FC),
                contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                prefixIcon: Icon(icon, color: hasValue ? AppConstants.primaryBlue : Colors.grey.shade500, size: 22),
                suffixIcon: isLoading
                    ? const SizedBox(
                        width: 20,
                        height: 20,
                        child: Center(
                          child: CircularProgressIndicator(strokeWidth: 2, color: AppConstants.primaryBlue),
                        ),
                      )
                    : Icon(Icons.arrow_drop_down_rounded, color: Colors.grey.shade600, size: 28),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: BorderSide(color: Colors.grey.shade200)),
                enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: BorderSide(color: Colors.grey.shade200)),
                focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: const BorderSide(color: AppConstants.primaryBlue, width: 2)),
              ),
              child: Text(
                _selectedLabel,
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: hasValue ? FontWeight.w600 : FontWeight.normal,
                  color: hasValue ? AppConstants.textDark : Colors.grey.shade400,
                ),
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _SearchModalSheet<T> extends StatefulWidget {
  final String title;
  final IconData icon;
  final List<SearchableSelectItem<T>> items;
  final T? selectedValue;
  final String emptyMessage;
  final ValueChanged<T> onSelected;

  const _SearchModalSheet({
    Key? key,
    required this.title,
    required this.icon,
    required this.items,
    required this.selectedValue,
    required this.emptyMessage,
    required this.onSelected,
  }) : super(key: key);

  @override
  State<_SearchModalSheet<T>> createState() => _SearchModalSheetState<T>();
}

class _SearchModalSheetState<T> extends State<_SearchModalSheet<T>> {
  final TextEditingController _searchController = TextEditingController();
  List<SearchableSelectItem<T>> _filteredItems = [];

  @override
  void initState() {
    super.initState();
    _filteredItems = widget.items;
  }

  void _onSearchChanged(String query) {
    final cleanQuery = query.toLowerCase().trim();
    setState(() {
      if (cleanQuery.isEmpty) {
        _filteredItems = widget.items;
      } else {
        _filteredItems = widget.items.where((item) {
          final labelMatches = item.label.toLowerCase().contains(cleanQuery);
          final subtitleMatches = item.subtitle?.toLowerCase().contains(cleanQuery) ?? false;
          return labelMatches || subtitleMatches;
        }).toList();
      }
    });
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final mediaQuery = MediaQuery.of(context);
    final sheetHeight = mediaQuery.size.height * 0.75;

    return Container(
      height: sheetHeight,
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: Column(
        children: [
          // Drag handle
          const SizedBox(height: 12),
          Container(
            width: 40,
            height: 4,
            decoration: BoxDecoration(
              color: Colors.grey.shade300,
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          const SizedBox(height: 12),

          // Header
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Row(
              children: [
                Icon(widget.icon, color: AppConstants.primaryBlue, size: 22),
                const SizedBox(width: 10),
                Text(
                  'Pilih ${widget.title}',
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: AppConstants.textDark,
                  ),
                ),
                const Spacer(),
                IconButton(
                  icon: const Icon(Icons.close_rounded, color: Colors.grey),
                  onPressed: () => Navigator.pop(context),
                ),
              ],
            ),
          ),

          // Search Field
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
            child: TextField(
              controller: _searchController,
              onChanged: _onSearchChanged,
              autofocus: true,
              style: const TextStyle(fontSize: 14),
              decoration: InputDecoration(
                hintText: 'Cari ${widget.title}...',
                hintStyle: TextStyle(color: Colors.grey.shade400, fontSize: 14),
                prefixIcon: const Icon(Icons.search_rounded, color: AppConstants.primaryBlue, size: 22),
                suffixIcon: _searchController.text.isNotEmpty
                    ? IconButton(
                        icon: const Icon(Icons.clear_rounded, size: 18),
                        onPressed: () {
                          _searchController.clear();
                          _onSearchChanged('');
                        },
                      )
                    : null,
                filled: true,
                fillColor: const Color(0xFFF1F5F9),
                contentPadding: const EdgeInsets.symmetric(vertical: 14, horizontal: 16),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(14), borderSide: BorderSide.none),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(14),
                  borderSide: const BorderSide(color: AppConstants.primaryBlue, width: 1.5),
                ),
              ),
            ),
          ),
          const Divider(height: 16),

          // List Items
          Expanded(
            child: _filteredItems.isEmpty
                ? Center(
                    child: Padding(
                      padding: const EdgeInsets.all(24.0),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.search_off_rounded, size: 48, color: Colors.grey.shade400),
                          const SizedBox(height: 12),
                          Text(
                            widget.emptyMessage,
                            textAlign: TextAlign.center,
                            style: TextStyle(color: Colors.grey.shade600, fontSize: 13.5),
                          ),
                        ],
                      ),
                    ),
                  )
                : ListView.separated(
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                    itemCount: _filteredItems.length,
                    separatorBuilder: (ctx, idx) => Divider(height: 1, color: Colors.grey.shade100, indent: 16, endIndent: 16),
                    itemBuilder: (ctx, index) {
                      final item = _filteredItems[index];
                      final isSelected = item.value == widget.selectedValue;

                      return ListTile(
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                        tileColor: isSelected ? AppConstants.primaryBlue.withOpacity(0.08) : Colors.transparent,
                        title: Text(
                          item.label,
                          style: TextStyle(
                            fontSize: 14,
                            fontWeight: isSelected ? FontWeight.bold : FontWeight.w500,
                            color: isSelected ? AppConstants.primaryBlue : AppConstants.textDark,
                          ),
                        ),
                        subtitle: item.subtitle != null
                            ? Text(
                                item.subtitle!,
                                style: TextStyle(fontSize: 12, color: Colors.grey.shade500),
                              )
                            : null,
                        trailing: isSelected
                            ? const Icon(Icons.check_circle_rounded, color: AppConstants.primaryBlue, size: 20)
                            : null,
                        onTap: () => widget.onSelected(item.value),
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
